/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.CHITIET;

import DTO.SizeDTO;
import static GUI.CHITIET.QuanLyMauJPanel.fetchAll;
import GUI.POPUP.SuaJFrame;
import GUI.QuanLyJPanel;
import GUI.RenderTable;
import GUI.Sweet.SweetAlert;
import GUI.Sweet.SweetFileChooser;
import static GUI.TongQuanJPanel.customTable;
import static GUI.TongQuanJPanel.setJTableColumnsWidth;
import GUI.changeColorOfCellTable;
import IO.Excel.SizeExcel;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class QuanLySizeJPanel extends javax.swing.JPanel {
    static DefaultTableModel listTableModel;
     Object[] columnNames ={"Mã size","Size",""};
     public SizeDTO currentSize = new SizeDTO();
    /**
     * Creates new form QuanLySizeJPanel
     */
    public void changeCell3(){
        
        for(int j = 0 ; j<tblSize.getRowCount();j++){
            
                
                tblSize.getColumnModel().getColumn(2).setCellRenderer(new changeColorOfCellTable(tblSize,j,2));

            
            
        }
        
    }      
    public QuanLySizeJPanel() {
        initComponents();
        customTable(tblSize,scpSize);
        ShowTable(tblSize,columnNames);
        changeCell3();
        pnlThem.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        pnlQuayVe.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));    
        
        lblMaSize.setText(quanlycuahanggiay.quanlycuahanggiay.SizeBUS.getLatest());
               
    }

        public void ShowTable(JTable table,Object[] columnName){
        listTableModel = new DefaultTableModel(columnNames,0);
        table.setDefaultRenderer(Object.class, new RenderTable());
        fetchAll();
    }
        
        public static void fetchAll(){
            String edit ="Sửa";
            listTableModel.setRowCount(0);
            quanlycuahanggiay.quanlycuahanggiay.SizeBUS.SizeList.forEach(Size ->{
                Vector row = new Vector();
                row.add(Size.getMaSize());
                row.add(Size.getTenSize());
                row.add(edit);
                listTableModel.addRow(row);
            });
            tblSize.setModel(listTableModel);
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlQuayVe = new GUI.Rounded();
        lblQuayVe = new javax.swing.JLabel();
        pnlThongTin = new GUI.Rounded();
        lblThongTinHoaDon = new javax.swing.JLabel();
        scpSize = new javax.swing.JScrollPane();
        tblSize = new javax.swing.JTable(){
            public boolean isCellEditable ( int row, int col)
            {
                return false;
            }

        };
        lblThongTinHoaDon1 = new javax.swing.JLabel();
        pnlThongTinHoaDon = new javax.swing.JPanel();
        lblTitleSize = new javax.swing.JLabel();
        lblTitleMaSize = new javax.swing.JLabel();
        lblMaSize = new javax.swing.JLabel();
        pnlThem = new GUI.Rounded();
        lblThem = new javax.swing.JLabel();
        txtSize = new javax.swing.JTextField();
        pnlXuatDuLieu = new GUI.Rounded();
        lblThem1 = new javax.swing.JLabel();
        pnlNhapDuLieu = new GUI.Rounded();
        lblThem2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(45, 47, 62));

        pnlQuayVe.setBackground(new java.awt.Color(45, 47, 62));
        pnlQuayVe.setForeground(new java.awt.Color(238, 38, 63));
        pnlQuayVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlQuayVeMouseClicked(evt);
            }
        });

        lblQuayVe.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblQuayVe.setForeground(new java.awt.Color(255, 255, 255));
        lblQuayVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-icon.png"))); // NOI18N
        lblQuayVe.setText("  Quay về");

        javax.swing.GroupLayout pnlQuayVeLayout = new javax.swing.GroupLayout(pnlQuayVe);
        pnlQuayVe.setLayout(pnlQuayVeLayout);
        pnlQuayVeLayout.setHorizontalGroup(
            pnlQuayVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuayVeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuayVe, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlQuayVeLayout.setVerticalGroup(
            pnlQuayVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQuayVe, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        pnlThongTin.setBackground(new java.awt.Color(45, 47, 62));
        pnlThongTin.setForeground(new java.awt.Color(53, 55, 70));
        pnlThongTin.setPreferredSize(new java.awt.Dimension(920, 750));

        lblThongTinHoaDon.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblThongTinHoaDon.setForeground(new java.awt.Color(210, 48, 44));
        lblThongTinHoaDon.setText("Thêm size");

        scpSize.setBackground(new java.awt.Color(53, 55, 70));
        scpSize.setForeground(new java.awt.Color(53, 55, 70));

        tblSize.setAutoCreateRowSorter(true);
        tblSize.setBackground(new java.awt.Color(53, 55, 70));
        tblSize.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tblSize.setForeground(new java.awt.Color(255, 255, 255));
        tblSize.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblSize.setFocusable(false);
        tblSize.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblSize.setRowHeight(25);
        tblSize.setSelectionBackground(new java.awt.Color(72, 74, 89));
        tblSize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSizeMouseClicked(evt);
            }
        });
        scpSize.setViewportView(tblSize);

        lblThongTinHoaDon1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblThongTinHoaDon1.setForeground(new java.awt.Color(210, 48, 44));
        lblThongTinHoaDon1.setText("Danh sách size");

        pnlThongTinHoaDon.setBackground(new java.awt.Color(53, 55, 70));
        pnlThongTinHoaDon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitleSize.setForeground(new java.awt.Color(192, 192, 192));
        lblTitleSize.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleSize.setText("Size:");
        pnlThongTinHoaDon.add(lblTitleSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        lblTitleMaSize.setForeground(new java.awt.Color(192, 192, 192));
        lblTitleMaSize.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleMaSize.setText("Mã size:");
        pnlThongTinHoaDon.add(lblTitleMaSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 70, -1));

        lblMaSize.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblMaSize.setForeground(new java.awt.Color(210, 48, 44));
        lblMaSize.setText("#SIZE1234");
        pnlThongTinHoaDon.add(lblMaSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, -8, -1, 30));

        pnlThem.setBackground(new java.awt.Color(53, 55, 70));
        pnlThem.setForeground(new java.awt.Color(210, 48, 44));

        lblThem.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblThem.setForeground(new java.awt.Color(255, 255, 255));
        lblThem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThem.setText("Thêm");
        lblThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThemMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlThemLayout = new javax.swing.GroupLayout(pnlThem);
        pnlThem.setLayout(pnlThemLayout);
        pnlThemLayout.setHorizontalGroup(
            pnlThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThemLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblThem, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnlThemLayout.setVerticalGroup(
            pnlThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblThem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pnlThongTinHoaDon.add(pnlThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, 30));

        txtSize.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtSize.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtSize.setBorder(null);
        txtSize.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSizeKeyPressed(evt);
            }
        });
        pnlThongTinHoaDon.add(txtSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 150, 20));

        pnlXuatDuLieu.setBackground(new java.awt.Color(53, 55, 70));
        pnlXuatDuLieu.setForeground(new java.awt.Color(210, 48, 44));

        lblThem1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblThem1.setForeground(new java.awt.Color(255, 255, 255));
        lblThem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThem1.setText("Xuất dữ liệu");
        lblThem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblThem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThem1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlXuatDuLieuLayout = new javax.swing.GroupLayout(pnlXuatDuLieu);
        pnlXuatDuLieu.setLayout(pnlXuatDuLieuLayout);
        pnlXuatDuLieuLayout.setHorizontalGroup(
            pnlXuatDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlXuatDuLieuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblThem1, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlXuatDuLieuLayout.setVerticalGroup(
            pnlXuatDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblThem1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pnlThongTinHoaDon.add(pnlXuatDuLieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, -1, 30));

        pnlNhapDuLieu.setBackground(new java.awt.Color(53, 55, 70));
        pnlNhapDuLieu.setForeground(new java.awt.Color(210, 48, 44));

        lblThem2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblThem2.setForeground(new java.awt.Color(255, 255, 255));
        lblThem2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThem2.setText("Nhập dữ liệu");
        lblThem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblThem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThem2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlNhapDuLieuLayout = new javax.swing.GroupLayout(pnlNhapDuLieu);
        pnlNhapDuLieu.setLayout(pnlNhapDuLieuLayout);
        pnlNhapDuLieuLayout.setHorizontalGroup(
            pnlNhapDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNhapDuLieuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblThem2, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlNhapDuLieuLayout.setVerticalGroup(
            pnlNhapDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblThem2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pnlThongTinHoaDon.add(pnlNhapDuLieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, -1, 30));

        javax.swing.GroupLayout pnlThongTinLayout = new javax.swing.GroupLayout(pnlThongTin);
        pnlThongTin.setLayout(pnlThongTinLayout);
        pnlThongTinLayout.setHorizontalGroup(
            pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addComponent(scpSize, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addComponent(lblThongTinHoaDon1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongTinLayout.createSequentialGroup()
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addComponent(lblThongTinHoaDon)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(pnlThongTinHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 863, Short.MAX_VALUE))
                        .addGap(17, 17, 17))))
        );
        pnlThongTinLayout.setVerticalGroup(
            pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblThongTinHoaDon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlThongTinHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblThongTinHoaDon1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scpSize, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlQuayVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(pnlQuayVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(pnlThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pnlQuayVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQuayVeMouseClicked
        this.removeAll();
        this.setLayout(new BorderLayout());
        this.add(new QuanLyJPanel());
        this.validate();
        this.repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_pnlQuayVeMouseClicked

    private void tblSizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSizeMouseClicked
        int column = tblSize.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tblSize.getRowHeight();

        if(row < tblSize.getRowCount() && row >= 0 && column < tblSize.getColumnCount() && column >= 0){
             currentSize = quanlycuahanggiay.quanlycuahanggiay.SizeBUS.getByMaSize(tblSize.getModel().getValueAt(row,0).toString());
            if(tblSize.getValueAt(row,column).toString().equalsIgnoreCase("Sửa")){ 
                new SuaJFrame(1,currentSize).setVisible(true);
                           
            }
            }        
    }//GEN-LAST:event_tblSizeMouseClicked

    private void lblThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemMouseClicked
       if (SwingUtilities.isLeftMouseButton(evt))
            add();
        
    }//GEN-LAST:event_lblThemMouseClicked

    private void txtSizeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSizeKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if(txtSize.getText().equals("")){GUI.Sweet.SweetAlert.showSweetAlert(new javax.swing.JFrame(), "Lỗi","Không được bỏ trống",1); return;}
            add();
        }
    }//GEN-LAST:event_txtSizeKeyPressed

    private void lblThem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThem1MouseClicked
        try {
            String path = SweetFileChooser.ExcelFileChooser();
            if(path==null){
                SweetAlert.showSweetAlert(new JFrame(), "Lỗi", "Vui lòng chọn file phù hợp", 1);
                return;
            }
            SizeExcel.ExportExcelFile(path, quanlycuahanggiay.quanlycuahanggiay.SizeBUS.SizeList);
            SweetAlert.showSweetAlert(new JFrame(), "Thành công", "xuất dữ liệu thành công", 0);
        } catch (IOException ex) {
            SweetAlert.showSweetAlert(new JFrame(), "Lỗi", ex.getMessage(), 1);
        }
    }//GEN-LAST:event_lblThem1MouseClicked

    private void lblThem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThem2MouseClicked
        try {
            String path = SweetFileChooser.ExcelFileChooser();
            if(path==null){
                SweetAlert.showSweetAlert(new JFrame(), "Lỗi", "Vui lòng chọn file phù hợp", 1);
                return;
            }
            SizeExcel.ImportExcelFile(path, 2).forEach(size->{
                if(quanlycuahanggiay.quanlycuahanggiay.SizeBUS.add(size)==false);
                    size.setMaSize(quanlycuahanggiay.quanlycuahanggiay.MauBUS.getLatest());
                    quanlycuahanggiay.quanlycuahanggiay.SizeBUS.add(size);
            });
            SweetAlert.showSweetAlert(new JFrame(), "Hoàn tất", "Nhập dữ liệu thành công", 0);
        } catch (IOException ex) {
            SweetAlert.showSweetAlert(new JFrame(), "Lỗi", ex.getMessage(), 1);
        }
        fetchAll();
    }//GEN-LAST:event_lblThem2MouseClicked
 
    private void setCurrentSize(){
        currentSize.setMaSize(lblMaSize.getText());
        currentSize.setTenSize(txtSize.getText());
    }
 
    private void add(){
        if(GUI.Sweet.SweetAlert.showSweetOption(new javax.swing.JFrame(), "Xác nhận", "Thêm mới?",0)==1){
        if(txtSize.getText().equals("")){GUI.Sweet.SweetAlert.showSweetAlert(new javax.swing.JFrame(), "Lỗi","Không được bỏ trống",1); return;}
        setCurrentSize();
        if(quanlycuahanggiay.quanlycuahanggiay.SizeBUS.add(currentSize)){
        fetchAll();
        fillBlank();
        lblMaSize.setText(quanlycuahanggiay.quanlycuahanggiay.SizeBUS.getLatest());
        }
        }
    }
    private void fillBlank(){
    txtSize.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblMaSize;
    private javax.swing.JLabel lblQuayVe;
    private javax.swing.JLabel lblThem;
    private javax.swing.JLabel lblThem1;
    private javax.swing.JLabel lblThem2;
    private javax.swing.JLabel lblThongTinHoaDon;
    private javax.swing.JLabel lblThongTinHoaDon1;
    private javax.swing.JLabel lblTitleMaSize;
    private javax.swing.JLabel lblTitleSize;
    private GUI.Rounded pnlNhapDuLieu;
    private GUI.Rounded pnlQuayVe;
    private GUI.Rounded pnlThem;
    private GUI.Rounded pnlThongTin;
    private javax.swing.JPanel pnlThongTinHoaDon;
    private GUI.Rounded pnlXuatDuLieu;
    private javax.swing.JScrollPane scpSize;
    private static javax.swing.JTable tblSize;
    private javax.swing.JTextField txtSize;
    // End of variables declaration//GEN-END:variables
}
