/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.THEMMOI;

import DTO.DonHangDTO;
import DTO.KhachHangDTO;
import DTO.SanPhamDTO;
import GUI.CHITIET.ChiTietDonHangJPanel;
import GUI.DonHangJPanel;
import GUI.POPUP.ThemSanPhamVaoDonHangJFrame;
import GUI.RenderTable;
import GUI.Sweet.SweetComboBox;
import static GUI.TongQuanJPanel.customTable;
import GUI.changeColorOfCellTable;
import java.awt.BorderLayout;
import java.awt.Cursor;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import quanlycuahanggiay.DateTime;
import static GUI.DonHangJPanel.currentDonHang;
import static GUI.DonHangJPanel.currentKhachHang;
import static GUI.DonHangJPanel.currentChiTietDonHangList;
import static GUI.DonHangJPanel.getTrangThai;
import static GUI.CHITIET.ChiTietDonHangJPanel.SanPhamList;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.TableModel;
import static quanlycuahanggiay.DateTime.TimestampToDateString;
import static quanlycuahanggiay.Currency.changeCurrency;

/**
 *
 * @author admin
 */
public class SuaDonHangJPanel extends javax.swing.JPanel {
    boolean option = true;
    static DefaultTableModel listTableModel;
    public KhachHangDTO KhachHang;
    public DonHangDTO DonHang;
    public SanPhamDTO SanPham;
    SweetComboBox cbxTrangThai;
    /**
     * Creates new form TaoDonHangJPanel
     */
    Object[] columnNames ={"Sản phẩm","Đơn giá","Số lượng","Size","Màu","Tạm tính",""};
    public void ShowTable(JTable table,Object[] columnName){
        listTableModel = new DefaultTableModel(columnNames,0);
        table.setDefaultRenderer(Object.class, new RenderTable());
        JButton del = new JButton();
        del.setName("xóa");
        fetchAll();
        //Object columnNames[] = columnName;
        //Object tensanpham[] = {"Adidas","Nike","Adidas","Nike","Adidas"};
        //Object dongia[] ={"3.600.000đ","3.600.000đ","3.600.000đ","3.600.000đ","3.600.000đ"};
        //Object soluong[] ={1,2,3,4,5};
        //Object size[] ={8,9,9,8,7};
        //Object mau[] = {"Hồng","Hồng","Hồng","Hồng","Hồng"};
        //Object tamtinh[] = {"3.600.000đ","3.600.000đ","3.600.000đ","3.600.000đ","3.600.000đ"};
        //for(int i=0 ; i<tensanpham.length ; i++){
        //        Object row[] = {tensanpham[i],dongia[i],soluong[i],size[i],mau[i],tamtinh[i],del};
        //        listTableModel.addRow(row);
        //    }        
        //table.setModel(listTableModel);
    }
   
    public void setComboBox(){
        String[] trangthai = {"Thành Công","Hủy"};
        cbxTrangThai = new SweetComboBox("#ffffff","#181818",0,0,130,30,trangthai);
        pnlTrangThai.add(cbxTrangThai);
       cbxTrangThai.setSelectedItem(getTrangThai(currentDonHang.getTrangThai()));
    }    

    public SuaDonHangJPanel(boolean option){
        if(!option){
            this.option = false;
        }
            initComponents();
            customTable(tblSanPham,scpSanPham);
            ShowTable(tblSanPham,columnNames);
            setComboBox();
            setData();
            //pnlHuyDon.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            pnlXacNhan.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            //lblMaDonHang.setText(quanlycuahanggiay.quanlycuahanggiay.DonHangBUS.getLatest());
            lblNgayDat.setText(DateTime.TimestampToDateString(DateTime.getCurrentTimestamp(),1)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void setData(){
       lblMaDonHang.setText(currentDonHang.getMaDonHang());
       System.out.println(currentDonHang.getMaDonHang());
       System.out.println(currentDonHang.getMaCode());
       lblNgayDat.setText(TimestampToDateString(currentDonHang.getNgayXuat(),1));
       lblMaGiamGia.setText(currentDonHang.getMaCode());
       lblHoTen.setText(currentKhachHang.getHoTen());
       lblSoDienThoai.setText(currentKhachHang.getSoDienThoai());
       lblEmail.setText(currentKhachHang.getEmail());
       lblDiaChi.setText(currentKhachHang.getDiaChi());
       lblTamTinh.setText(changeCurrency(currentDonHang.getTamTinh())+"đ");
       lblGiamGia.setText(changeCurrency(currentDonHang.getGiamGia())+"đ");
       lblPhiVanChuyen.setText(changeCurrency(currentDonHang.getPhiVanChuyen())+"đ");
       //Double TienTamTinh = Double.parseDouble(currentDonHang.getTongTien());
       //Double TienGiamGia = Double.parseDouble(currentDonHang.getTongTien());
       //Double TongTien = TienTamTinh - TienGiamGia + 30000;
       lblTongTien.setText(changeCurrency(currentDonHang.getTongTien())+"đ");
       fetchAll();
   }
    
    public static void fetchAll(){
        listTableModel.setRowCount(0);
        tblSanPham.setModel(GUI.CHITIET.ChiTietDonHangJPanel.listTableModel);
        
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlThongTin = new GUI.Rounded();
        scpSanPham = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable(){
            public boolean isCellEditable ( int row, int col)
            {
                return false;
            }

        };
        lblThongTinHoaDon1 = new javax.swing.JLabel();
        pnlTongTien = new javax.swing.JPanel();
        lblTitleTamTinh = new javax.swing.JLabel();
        lblTitleMaGiamGia = new javax.swing.JLabel();
        lblTitlePhiVanChuyen = new javax.swing.JLabel();
        lblTitleTong = new javax.swing.JLabel();
        lblTamTinh = new javax.swing.JLabel();
        lblGiamGia = new javax.swing.JLabel();
        lblPhiVanChuyen = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        pnlThongTinHoaDon = new javax.swing.JPanel();
        lblTitleNgayDat = new javax.swing.JLabel();
        lblTitleSoDienThoai = new javax.swing.JLabel();
        lblTitleDiaChi = new javax.swing.JLabel();
        lblTitleEmail = new javax.swing.JLabel();
        lblTitleHoTen = new javax.swing.JLabel();
        lblDiaChi = new javax.swing.JLabel();
        lblTitleTrangThai = new javax.swing.JLabel();
        lblTitleMaDonHang = new javax.swing.JLabel();
        lblTitleMaGiamGia1 = new javax.swing.JLabel();
        lblMaDonHang = new javax.swing.JLabel();
        lblNgayDat = new javax.swing.JLabel();
        pnlTrangThai = new javax.swing.JPanel();
        lblHoTen = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSoDienThoai = new javax.swing.JLabel();
        lblMaGiamGia = new javax.swing.JLabel();
        pnlXacNhan = new GUI.Rounded();
        lblXacNhan = new javax.swing.JLabel();

        setBackground(new java.awt.Color(45, 47, 62));

        pnlThongTin.setBackground(new java.awt.Color(45, 47, 62));
        pnlThongTin.setForeground(new java.awt.Color(53, 55, 70));
        pnlThongTin.setPreferredSize(new java.awt.Dimension(920, 750));

        scpSanPham.setBackground(new java.awt.Color(53, 55, 70));
        scpSanPham.setForeground(new java.awt.Color(53, 55, 70));

        tblSanPham.setAutoCreateRowSorter(true);
        tblSanPham.setBackground(new java.awt.Color(53, 55, 70));
        tblSanPham.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tblSanPham.setForeground(new java.awt.Color(255, 255, 255));
        tblSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblSanPham.setFocusable(false);
        tblSanPham.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblSanPham.setRowHeight(25);
        tblSanPham.setSelectionBackground(new java.awt.Color(72, 74, 89));
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        scpSanPham.setViewportView(tblSanPham);

        lblThongTinHoaDon1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblThongTinHoaDon1.setForeground(new java.awt.Color(210, 48, 44));
        lblThongTinHoaDon1.setText("Sản phẩm");

        pnlTongTien.setBackground(new java.awt.Color(53, 55, 70));

        lblTitleTamTinh.setBackground(new java.awt.Color(192, 192, 192));
        lblTitleTamTinh.setForeground(new java.awt.Color(192, 192, 192));
        lblTitleTamTinh.setText("Tạm tính");

        lblTitleMaGiamGia.setBackground(new java.awt.Color(192, 192, 192));
        lblTitleMaGiamGia.setForeground(new java.awt.Color(192, 192, 192));
        lblTitleMaGiamGia.setText("Mã giảm giá");

        lblTitlePhiVanChuyen.setBackground(new java.awt.Color(192, 192, 192));
        lblTitlePhiVanChuyen.setForeground(new java.awt.Color(192, 192, 192));
        lblTitlePhiVanChuyen.setText("Phí vận chuyển");

        lblTitleTong.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleTong.setText("Tổng");

        lblTamTinh.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblTamTinh.setForeground(new java.awt.Color(255, 255, 255));
        lblTamTinh.setText("3.600.000đ");

        lblGiamGia.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblGiamGia.setForeground(new java.awt.Color(255, 255, 255));
        lblGiamGia.setText("3.600.000đ");

        lblPhiVanChuyen.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblPhiVanChuyen.setForeground(new java.awt.Color(255, 255, 255));
        lblPhiVanChuyen.setText("3.600.000đ");

        lblTongTien.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblTongTien.setForeground(new java.awt.Color(210, 48, 44));
        lblTongTien.setText("3.600.000đ");

        javax.swing.GroupLayout pnlTongTienLayout = new javax.swing.GroupLayout(pnlTongTien);
        pnlTongTien.setLayout(pnlTongTienLayout);
        pnlTongTienLayout.setHorizontalGroup(
            pnlTongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTongTienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTongTienLayout.createSequentialGroup()
                        .addGroup(pnlTongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitleMaGiamGia)
                            .addComponent(lblTitlePhiVanChuyen)
                            .addComponent(lblTitleTong))
                        .addGap(48, 48, 48)
                        .addGroup(pnlTongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTongTien)
                            .addComponent(lblGiamGia)
                            .addComponent(lblPhiVanChuyen))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlTongTienLayout.createSequentialGroup()
                        .addComponent(lblTitleTamTinh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTamTinh)))
                .addContainerGap())
        );
        pnlTongTienLayout.setVerticalGroup(
            pnlTongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTongTienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlTongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleTamTinh)
                    .addComponent(lblTamTinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleMaGiamGia)
                    .addComponent(lblGiamGia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitlePhiVanChuyen)
                    .addComponent(lblPhiVanChuyen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleTong)
                    .addComponent(lblTongTien)))
        );

        pnlThongTinHoaDon.setBackground(new java.awt.Color(53, 55, 70));
        pnlThongTinHoaDon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitleNgayDat.setForeground(new java.awt.Color(192, 192, 192));
        lblTitleNgayDat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleNgayDat.setText("Ngày đặt:");
        pnlThongTinHoaDon.add(lblTitleNgayDat, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 70, -1));

        lblTitleSoDienThoai.setForeground(new java.awt.Color(192, 192, 192));
        lblTitleSoDienThoai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleSoDienThoai.setText("Số điện thoại:");
        pnlThongTinHoaDon.add(lblTitleSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        lblTitleDiaChi.setForeground(new java.awt.Color(192, 192, 192));
        lblTitleDiaChi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleDiaChi.setText("Địa chỉ:");
        pnlThongTinHoaDon.add(lblTitleDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        lblTitleEmail.setForeground(new java.awt.Color(192, 192, 192));
        lblTitleEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleEmail.setText("Email:");
        pnlThongTinHoaDon.add(lblTitleEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lblTitleHoTen.setForeground(new java.awt.Color(192, 192, 192));
        lblTitleHoTen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleHoTen.setText("Họ tên:");
        pnlThongTinHoaDon.add(lblTitleHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 50, -1));

        lblDiaChi.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblDiaChi.setForeground(new java.awt.Color(255, 255, 255));
        lblDiaChi.setText("Họ Văn Tên");
        pnlThongTinHoaDon.add(lblDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 157, 220, 20));

        lblTitleTrangThai.setForeground(new java.awt.Color(192, 192, 192));
        lblTitleTrangThai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleTrangThai.setText("Trạng thái:");
        pnlThongTinHoaDon.add(lblTitleTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 80, -1));

        lblTitleMaDonHang.setForeground(new java.awt.Color(192, 192, 192));
        lblTitleMaDonHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleMaDonHang.setText("Mã đơn hàng:");
        pnlThongTinHoaDon.add(lblTitleMaDonHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 90, -1));

        lblTitleMaGiamGia1.setForeground(new java.awt.Color(192, 192, 192));
        lblTitleMaGiamGia1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleMaGiamGia1.setText("Mã giảm giá:");
        pnlThongTinHoaDon.add(lblTitleMaGiamGia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 80, -1));

        lblMaDonHang.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblMaDonHang.setForeground(new java.awt.Color(210, 48, 44));
        lblMaDonHang.setText("12345");
        pnlThongTinHoaDon.add(lblMaDonHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, 20));

        lblNgayDat.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblNgayDat.setForeground(new java.awt.Color(255, 255, 255));
        lblNgayDat.setText("01/05/2000");
        pnlThongTinHoaDon.add(lblNgayDat, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, -1, -1));

        pnlTrangThai.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlTrangThaiLayout = new javax.swing.GroupLayout(pnlTrangThai);
        pnlTrangThai.setLayout(pnlTrangThaiLayout);
        pnlTrangThaiLayout.setHorizontalGroup(
            pnlTrangThaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        pnlTrangThaiLayout.setVerticalGroup(
            pnlTrangThaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        pnlThongTinHoaDon.add(pnlTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 130, 30));

        lblHoTen.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblHoTen.setForeground(new java.awt.Color(255, 255, 255));
        lblHoTen.setText("Họ Văn Tên");
        pnlThongTinHoaDon.add(lblHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 36, 220, 20));

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Họ Văn Tên");
        pnlThongTinHoaDon.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 76, 220, 20));

        lblSoDienThoai.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblSoDienThoai.setForeground(new java.awt.Color(255, 255, 255));
        lblSoDienThoai.setText("Họ Văn Tên");
        pnlThongTinHoaDon.add(lblSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 117, 220, 20));

        lblMaGiamGia.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblMaGiamGia.setForeground(new java.awt.Color(210, 48, 44));
        lblMaGiamGia.setText("Họ Văn Tên");
        pnlThongTinHoaDon.add(lblMaGiamGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 67, 220, 20));

        pnlXacNhan.setBackground(new java.awt.Color(53, 55, 70));
        pnlXacNhan.setForeground(new java.awt.Color(34, 212, 52));
        pnlXacNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlXacNhanMouseClicked(evt);
            }
        });

        lblXacNhan.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        lblXacNhan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblXacNhan.setText("Xác nhận");

        javax.swing.GroupLayout pnlXacNhanLayout = new javax.swing.GroupLayout(pnlXacNhan);
        pnlXacNhan.setLayout(pnlXacNhanLayout);
        pnlXacNhanLayout.setHorizontalGroup(
            pnlXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlXacNhanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlXacNhanLayout.setVerticalGroup(
            pnlXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlXacNhanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblXacNhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlThongTinLayout = new javax.swing.GroupLayout(pnlThongTin);
        pnlThongTin.setLayout(pnlThongTinLayout);
        pnlThongTinLayout.setHorizontalGroup(
            pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblThongTinHoaDon1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlThongTinLayout.createSequentialGroup()
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongTinLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(pnlXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlThongTinHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongTinLayout.createSequentialGroup()
                        .addContainerGap(17, Short.MAX_VALUE)
                        .addComponent(scpSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlThongTinLayout.setVerticalGroup(
            pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlThongTinHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblThongTinHoaDon1)
                .addGap(60, 60, 60)
                .addComponent(scpSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongTinLayout.createSequentialGroup()
                        .addComponent(pnlXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(pnlThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 751, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(pnlThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(29, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        int column = tblSanPham.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tblSanPham.getRowHeight();
        if(row < tblSanPham.getRowCount() && row >= 0 && column < tblSanPham.getColumnCount() && column >= 0){
            for(int i=0;i<tblSanPham.getColumnCount()-2;i++){
                System.out.println(tblSanPham.getModel().getValueAt(row,i));
            }
        }
    }//GEN-LAST:event_tblSanPhamMouseClicked
  
    public String getGiaTriTrangThai(){
        if(cbxTrangThai.getSelectedItem().toString().equals("Thành Công")) return "1";
        else return "0";
    }
    
    //private boolean isNull(){
    //    if(txtHoTen.getText().equals("") && txtEmail.getText().equals("") && txtSoDienThoai.getText().equals("") &&txtDiaChi.getText().equals(""))
    //    return true;
    //    return false;
    //}
    private void pnlXacNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlXacNhanMouseClicked
        if (SwingUtilities.isLeftMouseButton(evt)){
            if(GUI.Sweet.SweetAlert.showSweetOption(new javax.swing.JFrame(),"Thông báo","Bạn có giữ thay đổi?",0)==1){
                if(changeTrangThai()){
                System.out.println("change true");
                    if(cbxTrangThai.getSelectedIndex()==0){
                        for(int i=0;i<GUI.DonHangJPanel.currentChiTietDonHangList.size();i++){
                            SanPhamDTO sanpham = quanlycuahanggiay.quanlycuahanggiay.SanPhamBUS.getByMaSanPham(GUI.DonHangJPanel.currentChiTietDonHangList.get(i).getMaSanPham());
                            sanpham.setSoLuong(Integer.toString(Integer.parseInt(sanpham.getSoLuong())-Integer.parseInt(GUI.DonHangJPanel.currentChiTietDonHangList.get(i).getSoLuong())));
                            quanlycuahanggiay.quanlycuahanggiay.SanPhamBUS.edit(sanpham);
                        }
                    System.out.println("Thanh cong");
                    } else {
                        for(int i=0;i<GUI.DonHangJPanel.currentChiTietDonHangList.size();i++){
                            SanPhamDTO sanpham = quanlycuahanggiay.quanlycuahanggiay.SanPhamBUS.getByMaSanPham(GUI.DonHangJPanel.currentChiTietDonHangList.get(i).getMaSanPham());
                            sanpham.setSoLuong(Integer.toString(Integer.parseInt(sanpham.getSoLuong())+Integer.parseInt(GUI.DonHangJPanel.currentChiTietDonHangList.get(i).getSoLuong())));
                            quanlycuahanggiay.quanlycuahanggiay.SanPhamBUS.edit(sanpham);
                        }
                        System.out.println("Huy");
                    } 
                } else System.out.println("change false");
                currentDonHang.setTrangThai(getGiaTriTrangThai());
                quanlycuahanggiay.quanlycuahanggiay.DonHangBUS.edit(currentDonHang);
           } 
        }    
        this.removeAll();
        this.setLayout(new BorderLayout());        
        if(option){
            this.add(new ChiTietDonHangJPanel());            
        }
        else{
            this.add(new ChiTietDonHangJPanel()); 
        }

            this.validate();
            this.repaint();

    }//GEN-LAST:event_pnlXacNhanMouseClicked

public boolean changeTrangThai(){
        System.out.println("TrangThaiDH: "+currentDonHang.getTrangThai());
        System.out.println("CBX: "+cbxTrangThai.getSelectedIndex());
        return (currentDonHang.getTrangThai().equals(cbxTrangThai.getSelectedIndex())) ? false : true;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGiamGia;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblMaDonHang;
    private javax.swing.JLabel lblMaGiamGia;
    private javax.swing.JLabel lblNgayDat;
    private javax.swing.JLabel lblPhiVanChuyen;
    private javax.swing.JLabel lblSoDienThoai;
    private javax.swing.JLabel lblTamTinh;
    private javax.swing.JLabel lblThongTinHoaDon1;
    private javax.swing.JLabel lblTitleDiaChi;
    private javax.swing.JLabel lblTitleEmail;
    private javax.swing.JLabel lblTitleHoTen;
    private javax.swing.JLabel lblTitleMaDonHang;
    private javax.swing.JLabel lblTitleMaGiamGia;
    private javax.swing.JLabel lblTitleMaGiamGia1;
    private javax.swing.JLabel lblTitleNgayDat;
    private javax.swing.JLabel lblTitlePhiVanChuyen;
    private javax.swing.JLabel lblTitleSoDienThoai;
    private javax.swing.JLabel lblTitleTamTinh;
    private javax.swing.JLabel lblTitleTong;
    private javax.swing.JLabel lblTitleTrangThai;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JLabel lblXacNhan;
    private GUI.Rounded pnlThongTin;
    private javax.swing.JPanel pnlThongTinHoaDon;
    private javax.swing.JPanel pnlTongTien;
    private javax.swing.JPanel pnlTrangThai;
    private GUI.Rounded pnlXacNhan;
    private javax.swing.JScrollPane scpSanPham;
    private static javax.swing.JTable tblSanPham;
    // End of variables declaration//GEN-END:variables
}
