/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.THEMMOI;

import DTO.SanPhamDTO;
import GUI.SanPhamJPanel;
import GUI.Sweet.SweetComboBox;
import static GUI.Sweet.SweetFileChooser.PATH_SANPHAM;
import static GUI.Sweet.SweetImage.readImageFromFile;
import static GUI.Sweet.SweetImage.resizeImage;
import static GUI.Sweet.SweetImage.saveImage;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.SwingUtilities;
import static quanlycuahanggiay.Regexp.SoTuNhien;

/**
 *
 * @author admin
 */
public class TaoSanPhamJPanel extends javax.swing.JPanel {

    public SanPhamDTO SanPham;
    /**
     * Creates new form TaoSanPhamJPanel
     */
    SweetComboBox cbxMau, cbxSize, cbxThuongHieu;

    public void setComboBox() {
        String[] mau = quanlycuahanggiay.quanlycuahanggiay.MauBUS.getTenKhongTieuDeStringArray();
        cbxMau = new SweetComboBox("#ffffff", "#000000", 0, 0, 120, 30, mau);
        pnlMau.add(cbxMau);
        String[] size = quanlycuahanggiay.quanlycuahanggiay.SizeBUS.getTenKhongTieuDeStringArray();
        cbxSize = new SweetComboBox("#ffffff", "#000000", 0, 0, 90, 30, size);
        pnlSize.add(cbxSize);
        String[] thuonghieu = quanlycuahanggiay.quanlycuahanggiay.ThuongHieuBUS.getTenKhongTieuDeStringArray();
        cbxThuongHieu = new SweetComboBox("#ffffff", "#000000", 0, 0, 190, 30, thuonghieu);
        pnlThuongHieu.add(cbxThuongHieu);

    }

    public TaoSanPhamJPanel() {
        initComponents();
        setComboBox();
        lblAnh.setIcon(readImageFromFile(PATH_SANPHAM + "default.jpg", 350, 370)); 
        pnlXacNhan.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        pnlHuyBo.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblMaSanPham.setText(quanlycuahanggiay.quanlycuahanggiay.SanPhamBUS.getLatest());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public boolean ErrorCheck(){
        if(!SoTuNhien(txtDonGia.getText())){
            GUI.Sweet.SweetAlert.showSweetAlert(new javax.swing.JFrame(), "Lỗi", "Đơn giá không hợp lệ", 1);
            return false;
        }
        return true;
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddImage1 = new javax.swing.JLabel();
        lblTitleMaSanPham = new javax.swing.JLabel();
        lblTitleTenSanPham = new javax.swing.JLabel();
        lblTitleDonGia = new javax.swing.JLabel();
        lblTitleMau = new javax.swing.JLabel();
        lblTitleSize = new javax.swing.JLabel();
        lblTitleThuongHieu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTenSanPham = new javax.swing.JTextField();
        lblMaSanPham = new javax.swing.JLabel();
        pnlXacNhan = new GUI.Rounded();
        lblXacNhan = new javax.swing.JLabel();
        pnlHuyBo = new GUI.Rounded();
        lblHuyBo = new javax.swing.JLabel();
        pnlSize = new javax.swing.JPanel();
        pnlMau = new javax.swing.JPanel();
        pnlThuongHieu = new javax.swing.JPanel();
        txtDonGia = new javax.swing.JTextField();
        lblAnh = new javax.swing.JLabel();

        setBackground(new java.awt.Color(45, 47, 62));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddImage1.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 14)); // NOI18N
        lblAddImage1.setForeground(new java.awt.Color(255, 255, 255));
        lblAddImage1.setText("Thêm hình ảnh");
        lblAddImage1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        lblAddImage1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblAddImage1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddImage1MouseClicked(evt);
            }
        });
        add(lblAddImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 100, -1));

        lblTitleMaSanPham.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTitleMaSanPham.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleMaSanPham.setText("Mã sản phẩm:");
        lblTitleMaSanPham.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        add(lblTitleMaSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 100, 40));

        lblTitleTenSanPham.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTitleTenSanPham.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleTenSanPham.setText("Tên sản phẩm:");
        lblTitleTenSanPham.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        add(lblTitleTenSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 110, 40));

        lblTitleDonGia.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTitleDonGia.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleDonGia.setText("Đơn giá:");
        lblTitleDonGia.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        add(lblTitleDonGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 100, 40));

        lblTitleMau.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTitleMau.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleMau.setText("Màu:");
        lblTitleMau.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        add(lblTitleMau, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 40, 30));

        lblTitleSize.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTitleSize.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleSize.setText("Size:");
        lblTitleSize.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        add(lblTitleSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 40, 30));

        lblTitleThuongHieu.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTitleThuongHieu.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleThuongHieu.setText("Thương hiệu:");
        lblTitleThuongHieu.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        add(lblTitleThuongHieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 100, 40));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(210, 57, 44));
        jLabel1.setText("đ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, 30, 30));

        txtTenSanPham.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtTenSanPham.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTenSanPham.setBorder(null);
        add(txtTenSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 190, 30));

        lblMaSanPham.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblMaSanPham.setForeground(new java.awt.Color(210, 57, 44));
        lblMaSanPham.setText("#213");
        add(lblMaSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, -1, -1));

        pnlXacNhan.setBackground(new java.awt.Color(45, 47, 62));
        pnlXacNhan.setForeground(new java.awt.Color(34, 212, 52));
        pnlXacNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlXacNhanMouseClicked(evt);
            }
        });

        lblXacNhan.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        lblXacNhan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblXacNhan.setText("Thêm");

        javax.swing.GroupLayout pnlXacNhanLayout = new javax.swing.GroupLayout(pnlXacNhan);
        pnlXacNhan.setLayout(pnlXacNhanLayout);
        pnlXacNhanLayout.setHorizontalGroup(
            pnlXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlXacNhanLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlXacNhanLayout.setVerticalGroup(
            pnlXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlXacNhanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblXacNhan, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(pnlXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 650, 110, -1));

        pnlHuyBo.setBackground(new java.awt.Color(45, 47, 62));
        pnlHuyBo.setForeground(new java.awt.Color(238, 38, 64));
        pnlHuyBo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlHuyBoMouseClicked(evt);
            }
        });

        lblHuyBo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblHuyBo.setForeground(new java.awt.Color(255, 255, 255));
        lblHuyBo.setText("Hủy bỏ");

        javax.swing.GroupLayout pnlHuyBoLayout = new javax.swing.GroupLayout(pnlHuyBo);
        pnlHuyBo.setLayout(pnlHuyBoLayout);
        pnlHuyBoLayout.setHorizontalGroup(
            pnlHuyBoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHuyBoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblHuyBo)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnlHuyBoLayout.setVerticalGroup(
            pnlHuyBoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHuyBo, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        add(pnlHuyBo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, -1, -1));

        pnlSize.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlSizeLayout = new javax.swing.GroupLayout(pnlSize);
        pnlSize.setLayout(pnlSizeLayout);
        pnlSizeLayout.setHorizontalGroup(
            pnlSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        pnlSizeLayout.setVerticalGroup(
            pnlSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        add(pnlSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 90, 30));

        pnlMau.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlMauLayout = new javax.swing.GroupLayout(pnlMau);
        pnlMau.setLayout(pnlMauLayout);
        pnlMauLayout.setHorizontalGroup(
            pnlMauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        pnlMauLayout.setVerticalGroup(
            pnlMauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        add(pnlMau, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, -1, -1));

        pnlThuongHieu.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlThuongHieuLayout = new javax.swing.GroupLayout(pnlThuongHieu);
        pnlThuongHieu.setLayout(pnlThuongHieuLayout);
        pnlThuongHieuLayout.setHorizontalGroup(
            pnlThuongHieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        pnlThuongHieuLayout.setVerticalGroup(
            pnlThuongHieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        add(pnlThuongHieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, -1, -1));

        txtDonGia.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtDonGia.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDonGia.setBorder(null);
        add(txtDonGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 190, 30));

        lblAnh.setPreferredSize(new java.awt.Dimension(350, 250));
        add(lblAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 370));
    }// </editor-fold>//GEN-END:initComponents

    private void lblAddImage1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddImage1MouseClicked
        if (SwingUtilities.isLeftMouseButton(evt)) {
            try {
                File file =  GUI.Sweet.SweetFileChooser.ImageFileChooser();
                if(file!=null)
                lblAnh.setIcon(resizeImage(ImageIO.read(file),240,310));
            } catch (IOException ex) {
                Logger.getLogger(TaoSanPhamJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_lblAddImage1MouseClicked

    private void pnlXacNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlXacNhanMouseClicked


    if (SwingUtilities.isLeftMouseButton(evt)) {
        if (GUI.Sweet.SweetAlert.showSweetOption(new javax.swing.JFrame(), "Thêm mới tài khoản", "Xác nhận thêm?", 0) == 1) {
            if (isNotFill()) {
                GUI.Sweet.SweetAlert.showSweetAlert(new javax.swing.JFrame(), "Lỗi", "Không được bỏ trống", 0);
            } else {
                SanPham = new SanPhamDTO(   lblMaSanPham.getText(),
                                            txtTenSanPham.getText(),
                                            txtDonGia.getText(),
                                            "0",
                                            quanlycuahanggiay.quanlycuahanggiay.MauBUS.getMaMau(cbxMau.getSelectedItem().toString()),
                                            quanlycuahanggiay.quanlycuahanggiay.SizeBUS.getMaSize(cbxSize.getSelectedItem().toString()),
                                            quanlycuahanggiay.quanlycuahanggiay.ThuongHieuBUS.getMaThuongHieu(cbxThuongHieu.getSelectedItem().toString()),
                                            saveImage(lblMaSanPham.getText()));
                if (ErrorCheck()){
                if (quanlycuahanggiay.quanlycuahanggiay.SanPhamBUS.add(SanPham)) {
                    GUI.Sweet.SweetAlert.showSweetAlert(new javax.swing.JFrame(), "Thành Công", "Lưu thành công", 0);
                    fillBlank();
                    lblMaSanPham.setText(quanlycuahanggiay.quanlycuahanggiay.SanPhamBUS.getLatest());
            this.removeAll();
            this.setLayout(new BorderLayout());
            this.add(new SanPhamJPanel());
            this.validate();
            this.repaint();                    
                    GUI.SanPhamJPanel.fetchAll();
                }
                }
            }
        }
    }
    }//GEN-LAST:event_pnlXacNhanMouseClicked

    private boolean isNotFill() {
        if (txtTenSanPham.getText().equals("") || txtDonGia.getText().equals("")) {
            return true;
        }
        return false;
    }

    private void fillBlank() {
        txtDonGia.setText("");
        txtTenSanPham.setText("");
        lblAnh.setIcon(null);
    }

    private void pnlHuyBoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHuyBoMouseClicked
        this.removeAll();
        this.setLayout(new BorderLayout());
        this.add(new SanPhamJPanel());
        this.validate();
        this.repaint();
    }//GEN-LAST:event_pnlHuyBoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAddImage1;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JLabel lblHuyBo;
    private javax.swing.JLabel lblMaSanPham;
    private javax.swing.JLabel lblTitleDonGia;
    private javax.swing.JLabel lblTitleMaSanPham;
    private javax.swing.JLabel lblTitleMau;
    private javax.swing.JLabel lblTitleSize;
    private javax.swing.JLabel lblTitleTenSanPham;
    private javax.swing.JLabel lblTitleThuongHieu;
    private javax.swing.JLabel lblXacNhan;
    private GUI.Rounded pnlHuyBo;
    private javax.swing.JPanel pnlMau;
    private javax.swing.JPanel pnlSize;
    private javax.swing.JPanel pnlThuongHieu;
    private GUI.Rounded pnlXacNhan;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtTenSanPham;
    // End of variables declaration//GEN-END:variables
}
