/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.POPUP;

import DTO.SanPhamDTO;
import static GUI.THEMMOI.TaoDonHangJPanel.GioHang;
import static GUI.POPUP.ThemSanPhamVaoDonHangJFrame.SanPham;
import javax.swing.SwingUtilities;
import static quanlycuahanggiay.Regexp.So;
import static GUI.POPUP.ThemSanPhamVaoDonHangJFrame.currentChiTietDonHang;
import static GUI.POPUP.ThemSanPhamVaoDonHangJFrame.fetchAllBottom;
import static GUI.Sweet.SweetAlert.showSweetOption;
import java.awt.event.KeyEvent;

/**
 *
 * @author admin
 */
public class SoLuong extends javax.swing.JFrame {
    /**
     * Creates new form SoLuongVaDonGiaJFrame
     */
    int xMouse,yMouse;
    static long SoLuongMuaHopLe;
    public SoLuong() {
        SoLuongMuaHopLe = -1;
        initComponents();
        setLocationRelativeTo(null);
        ((javax.swing.JFrame) SwingUtilities.getWindowAncestor(GUI.THEMMOI.TaoDonHangJPanel.TSPVDHJF.getRootPane())).setEnabled(false);

    }
    
    public static void getSoLuongSanPhamBan(){
        String SoLuong = txtSoLuongSanPhamBan.getText();
        if(!So(SoLuong)){
            GUI.Sweet.SweetAlert.showSweetAlert(new javax.swing.JFrame(),"Lỗi!","Số lượng không hợp lệ",1);
            SoLuongMuaHopLe = -1;
        }
        else {
            long SoLuongBan = Long.parseLong(SoLuong);
            SanPhamDTO SanPham = quanlycuahanggiay.quanlycuahanggiay.SanPhamBUS.getByMaSanPham(currentChiTietDonHang.getMaSanPham());
            //System.out.println("SOLUONG: "+SanPham.getSoLuong());
            if(SoLuongBan > Long.parseLong(SanPham.getSoLuong())){
                GUI.Sweet.SweetAlert.showSweetAlert(new javax.swing.JFrame(),"Lỗi!","Số lượng mua vượt quá số lượng đang có",1);
                SoLuongMuaHopLe = -1;
            }
            else {
                SoLuongMuaHopLe = SoLuongBan;
                //return SoLuongMuaHopLe;
            }
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pnlSoLuongSanPhamNhap = new GUI.Rounded();
        txtSoLuongSanPhamBan = new javax.swing.JTextField();
        pnlThem = new GUI.Rounded();
        lblXacNhan = new javax.swing.JLabel();
        pnlHuy = new GUI.Rounded();
        lblHuy = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(45, 47, 62));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Số lượng sản phẩm nhập:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 30));

        pnlSoLuongSanPhamNhap.setBackground(new java.awt.Color(45, 47, 62));
        pnlSoLuongSanPhamNhap.setForeground(new java.awt.Color(255, 255, 255));
        pnlSoLuongSanPhamNhap.setFocusable(false);

        txtSoLuongSanPhamBan.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtSoLuongSanPhamBan.setForeground(new java.awt.Color(18, 18, 18));
        txtSoLuongSanPhamBan.setBorder(null);
        txtSoLuongSanPhamBan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSoLuongSanPhamBanKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout pnlSoLuongSanPhamNhapLayout = new javax.swing.GroupLayout(pnlSoLuongSanPhamNhap);
        pnlSoLuongSanPhamNhap.setLayout(pnlSoLuongSanPhamNhapLayout);
        pnlSoLuongSanPhamNhapLayout.setHorizontalGroup(
            pnlSoLuongSanPhamNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSoLuongSanPhamNhapLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtSoLuongSanPhamBan, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlSoLuongSanPhamNhapLayout.setVerticalGroup(
            pnlSoLuongSanPhamNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSoLuongSanPhamNhapLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtSoLuongSanPhamBan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(pnlSoLuongSanPhamNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 160, 30));

        pnlThem.setBackground(new java.awt.Color(45, 47, 62));
        pnlThem.setForeground(new java.awt.Color(34, 212, 52));
        pnlThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlThemMouseClicked(evt);
            }
        });
        pnlThem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblXacNhan.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        lblXacNhan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblXacNhan.setText("Thêm");
        pnlThem.add(lblXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 13, 120, -1));

        jPanel1.add(pnlThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 120, 50));

        pnlHuy.setBackground(new java.awt.Color(45, 47, 62));
        pnlHuy.setForeground(new java.awt.Color(255, 53, 53));
        pnlHuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlHuyMouseClicked(evt);
            }
        });
        pnlHuy.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHuy.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblHuy.setForeground(new java.awt.Color(255, 255, 255));
        lblHuy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHuy.setText("Hủy bỏ");
        pnlHuy.add(lblHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 13, 120, -1));

        jPanel1.add(pnlHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 120, 50));

        jLabel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel5MouseDragged(evt);
            }
        });
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThemMouseClicked
        Them();
        //((javax.swing.JFrame) SwingUtilities.getWindowAncestor(quanlycuahanggiay.quanlycuahanggiay.bg.getRootPane())).setEnabled(true);
        //((javax.swing.JFrame) SwingUtilities.getWindowAncestor(GUI.THEMMOI.TaoDonHangJPanel.ThemSanPhamVaoDonHangJFrame.getRootPane())).setEnabled(true);
    }//GEN-LAST:event_pnlThemMouseClicked

    public void Them(){
        long ThanhTien = 0;
        getSoLuongSanPhamBan();
        if(SoLuongMuaHopLe != -1 && SoLuongMuaHopLe != 0){
            if(GioHang.size()==0){
                Them1SanPham();
                /*
                ((javax.swing.JFrame) SwingUtilities.getWindowAncestor(quanlycuahanggiay.quanlycuahanggiay.bg)).setEnabled(true);
                currentChiTietDonHang.setSoLuong(SoLuongMuaHopLe+"");
                ThanhTien = SoLuongMuaHopLe*Integer.parseInt(GUI.POPUP.ThemSanPhamVaoDonHangJFrame.SanPham.getDonGia());
                currentChiTietDonHang.setThanhTien(Integer.toString(ThanhTien));
                GioHang.add(currentChiTietDonHang);
                ThemSanPhamVaoDonHangJFrame.fetchWhenAddingGioHang();
                fetchAllBottom();
                this.dispose();
                */
            }
            else{
                int flag = 1;
                for(int i=0;i<GioHang.size();i++){
                    if(GioHang.get(i).getMaSanPham().equals(SanPham.getMaSanPham())){
                        System.out.println("SP da co");
                        SoLuongMuaHopLe = Long.parseLong(GioHang.get(i).getSoLuong())+SoLuongMuaHopLe;
                        if(SoLuongMuaHopLe>Long.parseLong(SanPham.getSoLuong())){
                            GUI.Sweet.SweetAlert.showSweetAlert(new javax.swing.JFrame(),"Lỗi!","Tổng số lượng mua vượt quá số lượng hiện có",1);
                            return;
                        }
                        else{
                            long DonGia = Long.parseLong(SanPham.getDonGia());
                            GioHang.get(i).setSoLuong(SoLuongMuaHopLe+"");
                            System.out.println(SoLuongMuaHopLe);
                            System.out.println(DonGia);
                            GioHang.get(i).setThanhTien((tinhThanhTien(SoLuongMuaHopLe,DonGia)+""));
                            ThemSanPhamVaoDonHangJFrame.fetchWhenAddingGioHang();
                            fetchAllBottom();
                            flag = 0;
                            ((javax.swing.JFrame) SwingUtilities.getWindowAncestor(GUI.THEMMOI.TaoDonHangJPanel.TSPVDHJF.getRootPane())).setEnabled(true);
                            this.dispose();
      
                        }
                    }
                }
                if(flag == 1){
                    Them1SanPham();
                    /*
                    System.out.println("SP chua co");
                    ((javax.swing.JFrame) SwingUtilities.getWindowAncestor(quanlycuahanggiay.quanlycuahanggiay.bg)).setEnabled(true);
                    int DonGia = Integer.parseInt(SanPham.getDonGia());
                    currentChiTietDonHang.setSoLuong(SoLuongMuaHopLe+"");
                    currentChiTietDonHang.setThanhTien((tinhThanhTien(SoLuongMuaHopLe,DonGia)+""));
                    GioHang.add(currentChiTietDonHang);
                    ThemSanPhamVaoDonHangJFrame.fetchWhenAddingGioHang();
                    fetchAllBottom();
                    this.dispose();
                    */
                }
            } 
        }
        if(SoLuongMuaHopLe==0) GUI.Sweet.SweetAlert.showSweetAlert(new javax.swing.JFrame(),"Lỗi!","Số lượng mua không thể bằng 0",1);
    }
    
    public void Them1SanPham(){
        //((javax.swing.JFrame) SwingUtilities.getWindowAncestor(quanlycuahanggiay.quanlycuahanggiay.bg)).setEnabled(true);
        Long DonGia = Long.parseLong(SanPham.getDonGia());
        currentChiTietDonHang.setSoLuong(SoLuongMuaHopLe+"");
        currentChiTietDonHang.setThanhTien((tinhThanhTien(SoLuongMuaHopLe,DonGia)+""));
        GioHang.add(currentChiTietDonHang);
        ThemSanPhamVaoDonHangJFrame.fetchWhenAddingGioHang();
        fetchAllBottom();
        ((javax.swing.JFrame) SwingUtilities.getWindowAncestor(GUI.THEMMOI.TaoDonHangJPanel.TSPVDHJF.getRootPane())).setEnabled(true);
        this.dispose();
        //((javax.swing.JFrame) SwingUtilities.getWindowAncestor(GUI.POPUP.ThemSanPhamVaoDonHangJFrame.tblSanPham)).setEnabled(true);

    }
    
    public long tinhThanhTien(long SoLuong, long DonGia){
        return SoLuong*DonGia;
    }
    
    private void jLabel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y-yMouse);
    }//GEN-LAST:event_jLabel5MouseDragged

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jLabel5MousePressed

    private void pnlHuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHuyMouseClicked
        ((javax.swing.JFrame) SwingUtilities.getWindowAncestor(GUI.POPUP.ThemSanPhamVaoDonHangJFrame.tblSanPham)).setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_pnlHuyMouseClicked

    private void txtSoLuongSanPhamBanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoLuongSanPhamBanKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            Them();
            //((javax.swing.JFrame) SwingUtilities.getWindowAncestor(quanlycuahanggiay.quanlycuahanggiay.bg.getRootPane())).setEnabled(true);
            //((javax.swing.JFrame) SwingUtilities.getWindowAncestor(GUI.THEMMOI.TaoDonHangJPanel.ThemSanPhamVaoDonHangJFrame.getRootPane())).setEnabled(true);
        }
    }//GEN-LAST:event_txtSoLuongSanPhamBanKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SoLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SoLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SoLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SoLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SoLuong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHuy;
    private javax.swing.JLabel lblXacNhan;
    private GUI.Rounded pnlHuy;
    private GUI.Rounded pnlSoLuongSanPhamNhap;
    private GUI.Rounded pnlThem;
    private static javax.swing.JTextField txtSoLuongSanPhamBan;
    // End of variables declaration//GEN-END:variables
}
