/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.POPUP;

import DTO.ChuongTrinhKhuyenMaiDTO;
import GUI.KHUYENMAI.ChuongTrinhKhuyenMaiJPanel;
import static GUI.KHUYENMAI.ChuongTrinhKhuyenMaiJPanel.fetchAll;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import javax.swing.SwingUtilities;
import quanlycuahanggiay.DateTime;

/**
 *
 * @author admin
 */
public class TaoChuongTrinhKhuyenMaiJFrame extends javax.swing.JFrame {
    int xMouse,yMouse;
    public ChuongTrinhKhuyenMaiDTO ChuongTrinhKhuyenMai;
    /**
     * Creates new form TaoChuongTrinhKhuyenMaiJFrame
     */
    public TaoChuongTrinhKhuyenMaiJFrame() {
        SwingUtilities.getWindowAncestor(quanlycuahanggiay.quanlycuahanggiay.bg).setEnabled(false);
        
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);   
        pnlXacNhan.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        pnlHuyBo.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblMaChuongTrinhKhuyenMai.setText(quanlycuahanggiay.quanlycuahanggiay.ChuongTrinhKhuyenMaiBUS.getLatest());
    }
    public void XacNhan(){
        if (GUI.Sweet.SweetAlert.showSweetOption(new javax.swing.JFrame(), "Xác nhận", "Xác nhận thêm mới?", 1) == 1) {
            if (isNotFill()) {
                GUI.Sweet.SweetAlert.showSweetAlert(new javax.swing.JFrame(), "Lỗi", "Không được bỏ trống", 0);
            } else {
                ChuongTrinhKhuyenMai = new ChuongTrinhKhuyenMaiDTO(lblMaChuongTrinhKhuyenMai.getText(), txtTenChuongTrinhKhuyenMai.getText(), "1577865600");
                if(quanlycuahanggiay.quanlycuahanggiay.ChuongTrinhKhuyenMaiBUS.add(ChuongTrinhKhuyenMai)) {
                    GUI.Sweet.SweetAlert.showSweetAlert(new javax.swing.JFrame(), "Thành Công", "Lưu thành công", 0);
                    fillBlank();
                    lblMaChuongTrinhKhuyenMai.setText(quanlycuahanggiay.quanlycuahanggiay.ChuongTrinhKhuyenMaiBUS.getLatest());
                    ((javax.swing.JFrame) SwingUtilities.getWindowAncestor(quanlycuahanggiay.quanlycuahanggiay.bg)).setEnabled(true);
                    GUI.KHUYENMAI.ChuongTrinhKhuyenMaiJPanel.fetchAll();
                    this.dispose();
                }
            }
        }        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTaoChuongTrinhKhuyenMai = new javax.swing.JPanel();
        lblTenNhaCungCap1 = new javax.swing.JLabel();
        lblMaChuongTrinhKhuyenMai1 = new javax.swing.JLabel();
        lblMaChuongTrinhKhuyenMai = new javax.swing.JLabel();
        pnlXacNhan = new GUI.Rounded();
        lblThem = new javax.swing.JLabel();
        txtTenChuongTrinhKhuyenMai = new javax.swing.JTextField();
        lblTitleChinhSua = new javax.swing.JLabel();
        pnlHuyBo = new GUI.Rounded();
        lblHuyBo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        pnlTaoChuongTrinhKhuyenMai.setBackground(new java.awt.Color(53, 55, 70));
        pnlTaoChuongTrinhKhuyenMai.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTenNhaCungCap1.setForeground(new java.awt.Color(192, 192, 192));
        lblTenNhaCungCap1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTenNhaCungCap1.setText("Tên chương trình khuyến mãi:");
        pnlTaoChuongTrinhKhuyenMai.add(lblTenNhaCungCap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lblMaChuongTrinhKhuyenMai1.setForeground(new java.awt.Color(192, 192, 192));
        lblMaChuongTrinhKhuyenMai1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMaChuongTrinhKhuyenMai1.setText("Mã chương trình khuyến mãi:");
        pnlTaoChuongTrinhKhuyenMai.add(lblMaChuongTrinhKhuyenMai1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 190, -1));

        lblMaChuongTrinhKhuyenMai.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblMaChuongTrinhKhuyenMai.setForeground(new java.awt.Color(210, 48, 44));
        lblMaChuongTrinhKhuyenMai.setText("CT12345");
        pnlTaoChuongTrinhKhuyenMai.add(lblMaChuongTrinhKhuyenMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        pnlXacNhan.setBackground(new java.awt.Color(53, 55, 70));
        pnlXacNhan.setForeground(new java.awt.Color(37, 213, 54));
        pnlXacNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlXacNhanMouseClicked(evt);
            }
        });

        lblThem.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblThem.setForeground(new java.awt.Color(255, 255, 255));
        lblThem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThem.setText("Tạo chương trình");

        javax.swing.GroupLayout pnlXacNhanLayout = new javax.swing.GroupLayout(pnlXacNhan);
        pnlXacNhan.setLayout(pnlXacNhanLayout);
        pnlXacNhanLayout.setHorizontalGroup(
            pnlXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlXacNhanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlXacNhanLayout.setVerticalGroup(
            pnlXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblThem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlTaoChuongTrinhKhuyenMai.add(pnlXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 130, 40));

        txtTenChuongTrinhKhuyenMai.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtTenChuongTrinhKhuyenMai.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTenChuongTrinhKhuyenMai.setBorder(null);
        txtTenChuongTrinhKhuyenMai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTenChuongTrinhKhuyenMaiKeyPressed(evt);
            }
        });
        pnlTaoChuongTrinhKhuyenMai.add(txtTenChuongTrinhKhuyenMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 170, 20));

        lblTitleChinhSua.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblTitleChinhSua.setForeground(new java.awt.Color(210, 48, 44));
        lblTitleChinhSua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleChinhSua.setText("Tạo chương trình khuyến mãi");
        pnlTaoChuongTrinhKhuyenMai.add(lblTitleChinhSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 470, 30));

        pnlHuyBo.setBackground(new java.awt.Color(53, 55, 70));
        pnlHuyBo.setForeground(new java.awt.Color(238, 38, 63));
        pnlHuyBo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlHuyBoMouseClicked(evt);
            }
        });

        lblHuyBo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblHuyBo.setForeground(new java.awt.Color(255, 255, 255));
        lblHuyBo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHuyBo.setText("Hủy bỏ");

        javax.swing.GroupLayout pnlHuyBoLayout = new javax.swing.GroupLayout(pnlHuyBo);
        pnlHuyBo.setLayout(pnlHuyBoLayout);
        pnlHuyBoLayout.setHorizontalGroup(
            pnlHuyBoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHuyBoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHuyBo, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlHuyBoLayout.setVerticalGroup(
            pnlHuyBoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHuyBo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlTaoChuongTrinhKhuyenMai.add(pnlHuyBo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTaoChuongTrinhKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTaoChuongTrinhKhuyenMai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlXacNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlXacNhanMouseClicked
        XacNhan();
    }//GEN-LAST:event_pnlXacNhanMouseClicked
    
    private boolean isNotFill(){
        if(txtTenChuongTrinhKhuyenMai.getText().equals("")){
            return true;
        }
        return false;
    }
    
    private void fillBlank(){
        txtTenChuongTrinhKhuyenMai.setText("");
    }
    
    private void pnlHuyBoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHuyBoMouseClicked
        ((javax.swing.JFrame) SwingUtilities.getWindowAncestor(quanlycuahanggiay.quanlycuahanggiay.bg)).setEnabled(true);
        this.dispose();
        
    }//GEN-LAST:event_pnlHuyBoMouseClicked

    private void txtTenChuongTrinhKhuyenMaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenChuongTrinhKhuyenMaiKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
             XacNhan();
    }//GEN-LAST:event_txtTenChuongTrinhKhuyenMaiKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaoChuongTrinhKhuyenMaiJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaoChuongTrinhKhuyenMaiJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaoChuongTrinhKhuyenMaiJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaoChuongTrinhKhuyenMaiJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaoChuongTrinhKhuyenMaiJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblHuyBo;
    private javax.swing.JLabel lblMaChuongTrinhKhuyenMai;
    private javax.swing.JLabel lblMaChuongTrinhKhuyenMai1;
    private javax.swing.JLabel lblTenNhaCungCap1;
    private javax.swing.JLabel lblThem;
    private javax.swing.JLabel lblTitleChinhSua;
    private GUI.Rounded pnlHuyBo;
    private javax.swing.JPanel pnlTaoChuongTrinhKhuyenMai;
    private GUI.Rounded pnlXacNhan;
    private javax.swing.JTextField txtTenChuongTrinhKhuyenMai;
    // End of variables declaration//GEN-END:variables
}
