/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.KHUYENMAI;

import DTO.ChiTietKhuyenMaiDTO;
import DTO.ChuongTrinhKhuyenMaiDTO;
import GUI.KhuyenMaiJPanel;
import GUI.POPUP.TaoChuongTrinhKhuyenMaiJFrame;
import GUI.RenderTable;
import static GUI.TongQuanJPanel.customTable;
import GUI.changeColorOfCellTable;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import quanlycuahanggiay.DateTime;
import static quanlycuahanggiay.DateTime.TimestampToDateString;

/**
 *
 * @author admin
 */
public class ChuongTrinhKhuyenMaiJPanel extends javax.swing.JPanel {

    public static ChuongTrinhKhuyenMaiDTO currentChuongTrinhKhuyenMai;

    Object[] columnNames = {"Mã CT khuyến mãi ", "Tên CT khuyến mãi", "Ngày tạo", "Số lượng chi tiết khuyến mãi"};
    public static DefaultTableModel listTableModel;
    public ArrayList<ChuongTrinhKhuyenMaiDTO> arraySearch;

    /**
     * Creates new form ChuongTrinhKhuyenMaiJPanel
     */
    public void ShowTable(JTable table, Object[] columnName) {
        listTableModel = new DefaultTableModel(columnNames, 0);
        table.setDefaultRenderer(Object.class, new RenderTable());
        fetchAll();
    }

    public static void fetchAll() {
        listTableModel.setRowCount(0);
        quanlycuahanggiay.quanlycuahanggiay.ChuongTrinhKhuyenMaiBUS.ChuongTrinhKhuyenMaiList.forEach(ChuongTrinhKhuyenMai -> {
            Vector row = new Vector();
            row.add(ChuongTrinhKhuyenMai.getMaChuongTrinhKhuyenMai());
            row.add(ChuongTrinhKhuyenMai.getTenChuongTrinh());
            row.add(TimestampToDateString(ChuongTrinhKhuyenMai.getNgayTao(), 1));
            if (quanlycuahanggiay.quanlycuahanggiay.ChiTietKhuyenMaiBUS.getSoLuongbyMaChuongTrinhKhuyenMai(ChuongTrinhKhuyenMai.getMaChuongTrinhKhuyenMai()) == null) {
                row.add(0);
            }
            row.add(quanlycuahanggiay.quanlycuahanggiay.ChiTietKhuyenMaiBUS.getSoLuongbyMaChuongTrinhKhuyenMai(ChuongTrinhKhuyenMai.getMaChuongTrinhKhuyenMai()));
            listTableModel.addRow(row);
        });
        tblChuongTrinhKhuyenMai.setModel(listTableModel);

    }

    public ChuongTrinhKhuyenMaiJPanel() {
        initComponents();
        customTable(tblChuongTrinhKhuyenMai, scpDonHang);
        ShowTable(tblChuongTrinhKhuyenMai, columnNames);
        pnlTaoChuongTrinh.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        pnlQuayVe.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlTimKiemTenChuongTrinh = new GUI.Rounded();
        txtTimKiemTenChuongTrinh = new javax.swing.JTextField();
        pnlTimKiemMaChuongTrinh = new GUI.Rounded();
        txtTimKiemMaChuongTrinh = new javax.swing.JTextField();
        pnlTaoChuongTrinh = new GUI.Rounded();
        lblTaoPhieuNhap = new javax.swing.JLabel();
        pnlTblDonHangChuaXacNhan = new GUI.Rounded();
        scpDonHang = new javax.swing.JScrollPane();
        tblChuongTrinhKhuyenMai = new javax.swing.JTable(){
            public boolean isCellEditable ( int row, int col)
            {
                return false;
            }

        };
        pnlQuayVe = new GUI.Rounded();
        lblQuayVe = new javax.swing.JLabel();

        setBackground(new java.awt.Color(45, 47, 62));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mã chương trình:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 30));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tên chương trình:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 30));

        pnlTimKiemTenChuongTrinh.setBackground(new java.awt.Color(45, 47, 62));
        pnlTimKiemTenChuongTrinh.setForeground(new java.awt.Color(62, 64, 78));
        pnlTimKiemTenChuongTrinh.setFocusable(false);
        pnlTimKiemTenChuongTrinh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTimKiemTenChuongTrinh.setBackground(new java.awt.Color(62, 64, 78));
        txtTimKiemTenChuongTrinh.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTimKiemTenChuongTrinh.setForeground(new java.awt.Color(192, 192, 192));
        txtTimKiemTenChuongTrinh.setBorder(null);
        txtTimKiemTenChuongTrinh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemTenChuongTrinhKeyReleased(evt);
            }
        });
        pnlTimKiemTenChuongTrinh.add(txtTimKiemTenChuongTrinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 435, 30));

        add(pnlTimKiemTenChuongTrinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 115, 470, 30));

        pnlTimKiemMaChuongTrinh.setBackground(new java.awt.Color(45, 47, 62));
        pnlTimKiemMaChuongTrinh.setForeground(new java.awt.Color(62, 64, 78));
        pnlTimKiemMaChuongTrinh.setFocusable(false);
        pnlTimKiemMaChuongTrinh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTimKiemMaChuongTrinh.setBackground(new java.awt.Color(62, 64, 78));
        txtTimKiemMaChuongTrinh.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTimKiemMaChuongTrinh.setForeground(new java.awt.Color(192, 192, 192));
        txtTimKiemMaChuongTrinh.setBorder(null);
        txtTimKiemMaChuongTrinh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemMaChuongTrinhKeyReleased(evt);
            }
        });
        pnlTimKiemMaChuongTrinh.add(txtTimKiemMaChuongTrinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 448, 30));

        add(pnlTimKiemMaChuongTrinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 470, 30));

        pnlTaoChuongTrinh.setBackground(new java.awt.Color(45, 47, 62));
        pnlTaoChuongTrinh.setForeground(new java.awt.Color(210, 48, 44));
        pnlTaoChuongTrinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTaoChuongTrinhMouseClicked(evt);
            }
        });

        lblTaoPhieuNhap.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblTaoPhieuNhap.setForeground(new java.awt.Color(255, 255, 255));
        lblTaoPhieuNhap.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTaoPhieuNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        lblTaoPhieuNhap.setText("Tạo chương trình");

        javax.swing.GroupLayout pnlTaoChuongTrinhLayout = new javax.swing.GroupLayout(pnlTaoChuongTrinh);
        pnlTaoChuongTrinh.setLayout(pnlTaoChuongTrinhLayout);
        pnlTaoChuongTrinhLayout.setHorizontalGroup(
            pnlTaoChuongTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaoChuongTrinhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTaoPhieuNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTaoChuongTrinhLayout.setVerticalGroup(
            pnlTaoChuongTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTaoPhieuNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(pnlTaoChuongTrinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, -1, 40));

        pnlTblDonHangChuaXacNhan.setBackground(new java.awt.Color(45, 47, 62));
        pnlTblDonHangChuaXacNhan.setForeground(new java.awt.Color(53, 55, 70));

        scpDonHang.setBackground(new java.awt.Color(53, 55, 70));

        tblChuongTrinhKhuyenMai.setAutoCreateRowSorter(true);
        tblChuongTrinhKhuyenMai.setBackground(new java.awt.Color(53, 55, 70));
        tblChuongTrinhKhuyenMai.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tblChuongTrinhKhuyenMai.setForeground(new java.awt.Color(255, 255, 255));
        tblChuongTrinhKhuyenMai.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblChuongTrinhKhuyenMai.setFocusable(false);
        tblChuongTrinhKhuyenMai.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblChuongTrinhKhuyenMai.setRowHeight(25);
        tblChuongTrinhKhuyenMai.setSelectionBackground(new java.awt.Color(72, 74, 89));
        tblChuongTrinhKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChuongTrinhKhuyenMaiMouseClicked(evt);
            }
        });
        scpDonHang.setViewportView(tblChuongTrinhKhuyenMai);

        javax.swing.GroupLayout pnlTblDonHangChuaXacNhanLayout = new javax.swing.GroupLayout(pnlTblDonHangChuaXacNhan);
        pnlTblDonHangChuaXacNhan.setLayout(pnlTblDonHangChuaXacNhanLayout);
        pnlTblDonHangChuaXacNhanLayout.setHorizontalGroup(
            pnlTblDonHangChuaXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTblDonHangChuaXacNhanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpDonHang, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTblDonHangChuaXacNhanLayout.setVerticalGroup(
            pnlTblDonHangChuaXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTblDonHangChuaXacNhanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        add(pnlTblDonHangChuaXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 238, 870, 480));

        pnlQuayVe.setBackground(new java.awt.Color(45, 47, 62));
        pnlQuayVe.setForeground(new java.awt.Color(210, 48, 44));
        pnlQuayVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlQuayVeMouseClicked(evt);
            }
        });

        lblQuayVe.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblQuayVe.setForeground(new java.awt.Color(255, 255, 255));
        lblQuayVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-icon.png"))); // NOI18N
        lblQuayVe.setText("  Quay về");

        javax.swing.GroupLayout pnlQuayVeLayout = new javax.swing.GroupLayout(pnlQuayVe);
        pnlQuayVe.setLayout(pnlQuayVeLayout);
        pnlQuayVeLayout.setHorizontalGroup(
            pnlQuayVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuayVeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuayVe, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlQuayVeLayout.setVerticalGroup(
            pnlQuayVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQuayVe, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        add(pnlQuayVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void pnlTaoChuongTrinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTaoChuongTrinhMouseClicked

        new TaoChuongTrinhKhuyenMaiJFrame().setVisible(true);
    }//GEN-LAST:event_pnlTaoChuongTrinhMouseClicked

    public void search() {
        listTableModel.setRowCount(0);
        arraySearch.forEach(ChuongTrinhKhuyenMai -> {
            Vector row = new Vector();
            row.add(ChuongTrinhKhuyenMai.getMaChuongTrinhKhuyenMai());
            row.add(ChuongTrinhKhuyenMai.getTenChuongTrinh());
            row.add(DateTime.TimestampToDateString(ChuongTrinhKhuyenMai.getNgayTao(), 1));
            if (quanlycuahanggiay.quanlycuahanggiay.ChiTietKhuyenMaiBUS.getSoLuongbyMaChuongTrinhKhuyenMai(ChuongTrinhKhuyenMai.getMaChuongTrinhKhuyenMai()) == null) {
                row.add(0);
            }
            row.add(quanlycuahanggiay.quanlycuahanggiay.ChiTietKhuyenMaiBUS.getSoLuongbyMaChuongTrinhKhuyenMai(ChuongTrinhKhuyenMai.getMaChuongTrinhKhuyenMai()));
            listTableModel.addRow(row);
        });
        tblChuongTrinhKhuyenMai.setModel(listTableModel);
    }
    private void tblChuongTrinhKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChuongTrinhKhuyenMaiMouseClicked
        int column = tblChuongTrinhKhuyenMai.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tblChuongTrinhKhuyenMai.getRowHeight();

        if (row < tblChuongTrinhKhuyenMai.getRowCount() && row >= 0 && column < tblChuongTrinhKhuyenMai.getColumnCount() && column >= 0) {
            this.removeAll();
            this.setLayout(new BorderLayout());
            currentChuongTrinhKhuyenMai = quanlycuahanggiay.quanlycuahanggiay.ChuongTrinhKhuyenMaiBUS.getByMaChuongTrinhKhuyenMai((String) tblChuongTrinhKhuyenMai.getModel().getValueAt(row, 0));
            this.add(new ThongTinChuongTrinhKhuyenMaiJPanel());
            this.validate();
            this.repaint();

        }
    }//GEN-LAST:event_tblChuongTrinhKhuyenMaiMouseClicked

    private void getAdvancedSearch() {
        HashMap<String, String> advancedSearch = new HashMap<>();
        advancedSearch.put("MaChuongTrinhKhuyenMai", txtTimKiemMaChuongTrinh.getText());
        advancedSearch.put("TenChuongTrinhKhuyenMai", txtTimKiemTenChuongTrinh.getText());
        arraySearch = quanlycuahanggiay.quanlycuahanggiay.ChuongTrinhKhuyenMaiBUS.advancedSearch(advancedSearch);
        search();
    }
    private void pnlQuayVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQuayVeMouseClicked

        this.removeAll();
        this.setLayout(new BorderLayout());
        this.add(new KhuyenMaiJPanel());
        this.validate();
        this.repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_pnlQuayVeMouseClicked

    private void txtTimKiemTenChuongTrinhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemTenChuongTrinhKeyReleased
        getAdvancedSearch();
    }//GEN-LAST:event_txtTimKiemTenChuongTrinhKeyReleased

    private void txtTimKiemMaChuongTrinhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemMaChuongTrinhKeyReleased
        getAdvancedSearch();
    }//GEN-LAST:event_txtTimKiemMaChuongTrinhKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblQuayVe;
    private javax.swing.JLabel lblTaoPhieuNhap;
    private GUI.Rounded pnlQuayVe;
    private GUI.Rounded pnlTaoChuongTrinh;
    private GUI.Rounded pnlTblDonHangChuaXacNhan;
    private GUI.Rounded pnlTimKiemMaChuongTrinh;
    private GUI.Rounded pnlTimKiemTenChuongTrinh;
    private javax.swing.JScrollPane scpDonHang;
    private static javax.swing.JTable tblChuongTrinhKhuyenMai;
    private javax.swing.JTextField txtTimKiemMaChuongTrinh;
    private javax.swing.JTextField txtTimKiemTenChuongTrinh;
    // End of variables declaration//GEN-END:variables
}
