/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.KHUYENMAI;

import DTO.ChiTietKhuyenMaiDTO;
import DTO.ChuongTrinhKhuyenMaiDTO;
import DTO.DonHangDTO;

import static GUI.KHUYENMAI.ChuongTrinhKhuyenMaiJPanel.currentChuongTrinhKhuyenMai;
import GUI.RenderTable;
import static GUI.TongQuanJPanel.customTable;

import java.awt.BorderLayout;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static quanlycuahanggiay.DateTime.TimestampToDateString;
import static quanlycuahanggiay.Currency.changeCurrency;

/**
 *
 * @author admin
 */
public class ThongTinChuongTrinhKhuyenMaiJPanel extends javax.swing.JPanel {
    Object[] columnNames ={"Mã CT khuyến mãi","Mã code","Số lượng","% khuyến mãi","Giá tiền khuyến mãi","Ngày tạo"};
    /**
     * Creates new form ThongTinChuongTrinhKhuyenMai
     */
    
    public static DonHangDTO currentDonHang;
    public ArrayList<ChuongTrinhKhuyenMaiDTO> arraySearch;
    static DefaultTableModel listTableModel;
    public static ChiTietKhuyenMaiDTO currentChiTietKhuyenMai;
    
    public void ShowTable(JTable table,Object[] columnName){
        listTableModel = new DefaultTableModel(columnNames,0);
        table.setDefaultRenderer(Object.class, new RenderTable());
        fetchAll();
        
    }
    
    public static void fetchAll(){
        listTableModel.setRowCount(0);
        quanlycuahanggiay.quanlycuahanggiay.ChiTietKhuyenMaiBUS.ChiTietKhuyenMaiList.forEach(ChiTietKhuyenMai ->{
            if(ChiTietKhuyenMai.getMaChuongTrinhKhuyenMai().equals(currentChuongTrinhKhuyenMai.getMaChuongTrinhKhuyenMai())){
            Vector row = new Vector();
            row.add(ChiTietKhuyenMai.getMaChiTietKhuyenMai());
            row.add(ChiTietKhuyenMai.getMaCode());
            row.add(ChiTietKhuyenMai.getSoLuong());
            row.add(ChiTietKhuyenMai.getPhanTramKhuyenMai());
            row.add(changeCurrency(ChiTietKhuyenMai.getGiaTienKhuyenMai())+" đ");
            row.add(TimestampToDateString(currentChuongTrinhKhuyenMai.getNgayTao(),1));
            listTableModel.addRow(row);
            }
        });
        tblChiTietKhuyenMai.setModel(listTableModel);
    }
    
    private void setData(){
        lblMaChuongTrinhKhuyenMai.setText(currentChuongTrinhKhuyenMai.getMaChuongTrinhKhuyenMai());
        lblTenChuongTrinhKhuyenMai.setText(currentChuongTrinhKhuyenMai.getTenChuongTrinh());
        if(quanlycuahanggiay.quanlycuahanggiay.ChiTietKhuyenMaiBUS.getSoLuongbyMaChuongTrinhKhuyenMai(currentChuongTrinhKhuyenMai.getMaChuongTrinhKhuyenMai())==null){
            lblSoLuong.setText("0");
        }
        else{
        lblSoLuong.setText(quanlycuahanggiay.quanlycuahanggiay.ChiTietKhuyenMaiBUS.getSoLuongbyMaChuongTrinhKhuyenMai(currentChuongTrinhKhuyenMai.getMaChuongTrinhKhuyenMai()));
        }
        lblThoiGianTao.setText(TimestampToDateString(currentChuongTrinhKhuyenMai.getNgayTao(), 1));
    }
    
    public ThongTinChuongTrinhKhuyenMaiJPanel() {
        initComponents();
        customTable(tblChiTietKhuyenMai,scpChiTietKhuyenMai);
        ShowTable(tblChiTietKhuyenMai,columnNames);
        pnlQuayVe.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        setData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlThongTin2 = new GUI.Rounded();
        lblThongTinMaKhuyenMai2 = new javax.swing.JLabel();
        scpChiTietKhuyenMai = new javax.swing.JScrollPane();
        tblChiTietKhuyenMai = new javax.swing.JTable(){
            public boolean isCellEditable ( int row, int col)
            {
                return false;
            }

        };
        lblDonHang = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblThoiGianTao = new javax.swing.JLabel();
        lblTitleThoiGianTao = new javax.swing.JLabel();
        lblTitleTenChuongTrinhKhuyenMai = new javax.swing.JLabel();
        lblTenChuongTrinhKhuyenMai = new javax.swing.JLabel();
        lblTitleMaChuongTrinhKhuyenMai = new javax.swing.JLabel();
        lblMaChuongTrinhKhuyenMai = new javax.swing.JLabel();
        lblTitleSoLuong = new javax.swing.JLabel();
        lblSoLuong = new javax.swing.JLabel();
        pnlQuayVe = new GUI.Rounded();
        lblQuayVe = new javax.swing.JLabel();

        setBackground(new java.awt.Color(45, 47, 62));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlThongTin2.setBackground(new java.awt.Color(45, 47, 62));
        pnlThongTin2.setForeground(new java.awt.Color(53, 55, 70));
        pnlThongTin2.setPreferredSize(new java.awt.Dimension(920, 750));

        lblThongTinMaKhuyenMai2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblThongTinMaKhuyenMai2.setForeground(new java.awt.Color(210, 48, 44));
        lblThongTinMaKhuyenMai2.setText("Thông tin chương trình khuyến mãi");

        scpChiTietKhuyenMai.setBackground(new java.awt.Color(53, 55, 70));
        scpChiTietKhuyenMai.setForeground(new java.awt.Color(53, 55, 70));

        tblChiTietKhuyenMai.setAutoCreateRowSorter(true);
        tblChiTietKhuyenMai.setBackground(new java.awt.Color(53, 55, 70));
        tblChiTietKhuyenMai.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tblChiTietKhuyenMai.setForeground(new java.awt.Color(255, 255, 255));
        tblChiTietKhuyenMai.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblChiTietKhuyenMai.setFocusable(false);
        tblChiTietKhuyenMai.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblChiTietKhuyenMai.setRowHeight(25);
        tblChiTietKhuyenMai.setSelectionBackground(new java.awt.Color(72, 74, 89));
        tblChiTietKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChiTietKhuyenMaiMouseClicked(evt);
            }
        });
        scpChiTietKhuyenMai.setViewportView(tblChiTietKhuyenMai);

        lblDonHang.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblDonHang.setForeground(new java.awt.Color(210, 48, 44));
        lblDonHang.setText("Chi tiết khuyến mãi");

        jPanel1.setBackground(new java.awt.Color(53, 55, 70));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblThoiGianTao.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblThoiGianTao.setForeground(new java.awt.Color(255, 255, 255));
        lblThoiGianTao.setText("01/05/2000");
        jPanel1.add(lblThoiGianTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        lblTitleThoiGianTao.setForeground(new java.awt.Color(192, 192, 192));
        lblTitleThoiGianTao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleThoiGianTao.setText("Thời gian tạo:");
        jPanel1.add(lblTitleThoiGianTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        lblTitleTenChuongTrinhKhuyenMai.setForeground(new java.awt.Color(192, 192, 192));
        lblTitleTenChuongTrinhKhuyenMai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleTenChuongTrinhKhuyenMai.setText("Tên chương trình:");
        jPanel1.add(lblTitleTenChuongTrinhKhuyenMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 190, 30));

        lblTenChuongTrinhKhuyenMai.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblTenChuongTrinhKhuyenMai.setForeground(new java.awt.Color(255, 255, 255));
        lblTenChuongTrinhKhuyenMai.setText("Tên chương trình");
        jPanel1.add(lblTenChuongTrinhKhuyenMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, 30));

        lblTitleMaChuongTrinhKhuyenMai.setForeground(new java.awt.Color(192, 192, 192));
        lblTitleMaChuongTrinhKhuyenMai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleMaChuongTrinhKhuyenMai.setText("Mã chương trình khuyến mãi:");
        jPanel1.add(lblTitleMaChuongTrinhKhuyenMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 190, -1));

        lblMaChuongTrinhKhuyenMai.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblMaChuongTrinhKhuyenMai.setForeground(new java.awt.Color(210, 48, 44));
        lblMaChuongTrinhKhuyenMai.setText("#CT123");
        jPanel1.add(lblMaChuongTrinhKhuyenMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, -1));

        lblTitleSoLuong.setForeground(new java.awt.Color(192, 192, 192));
        lblTitleSoLuong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleSoLuong.setText("Số lượng chi tiết khuyến mãi:");
        jPanel1.add(lblTitleSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        lblSoLuong.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblSoLuong.setForeground(new java.awt.Color(255, 255, 255));
        lblSoLuong.setText("500");
        jPanel1.add(lblSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        javax.swing.GroupLayout pnlThongTin2Layout = new javax.swing.GroupLayout(pnlThongTin2);
        pnlThongTin2.setLayout(pnlThongTin2Layout);
        pnlThongTin2Layout.setHorizontalGroup(
            pnlThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTin2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scpChiTietKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblThongTinMaKhuyenMai2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDonHang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        pnlThongTin2Layout.setVerticalGroup(
            pnlThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTin2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblThongTinMaKhuyenMai2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDonHang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scpChiTietKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        add(pnlThongTin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 57, 890, 665));

        pnlQuayVe.setBackground(new java.awt.Color(45, 47, 62));
        pnlQuayVe.setForeground(new java.awt.Color(210, 48, 44));
        pnlQuayVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlQuayVeMouseClicked(evt);
            }
        });

        lblQuayVe.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblQuayVe.setForeground(new java.awt.Color(255, 255, 255));
        lblQuayVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-icon.png"))); // NOI18N
        lblQuayVe.setText("  Quay về");

        javax.swing.GroupLayout pnlQuayVeLayout = new javax.swing.GroupLayout(pnlQuayVe);
        pnlQuayVe.setLayout(pnlQuayVeLayout);
        pnlQuayVeLayout.setHorizontalGroup(
            pnlQuayVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuayVeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuayVe, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlQuayVeLayout.setVerticalGroup(
            pnlQuayVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQuayVe, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        add(pnlQuayVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 18, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tblChiTietKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChiTietKhuyenMaiMouseClicked
        int column = tblChiTietKhuyenMai.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tblChiTietKhuyenMai.getRowHeight();

        if(row < tblChiTietKhuyenMai.getRowCount() && row >= 0 && column < tblChiTietKhuyenMai.getColumnCount() && column >= 0){
                this.removeAll();
                this.setLayout(new BorderLayout());
                currentChiTietKhuyenMai = quanlycuahanggiay.quanlycuahanggiay.ChiTietKhuyenMaiBUS.getByMaChiTietKhuyenMai((String) tblChiTietKhuyenMai.getModel().getValueAt(row, 0));
                
                currentDonHang = quanlycuahanggiay.quanlycuahanggiay.DonHangBUS.getByMaDonHang((String) tblChiTietKhuyenMai.getModel().getValueAt(row, 0));
                this.add(new ThongTinChiTietKhuyenMaiTrongChuongTrinhKMJPanel());
                this.validate();
                this.repaint();               
        }
    }//GEN-LAST:event_tblChiTietKhuyenMaiMouseClicked

    private void pnlQuayVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQuayVeMouseClicked
        this.removeAll();
        this.setLayout(new BorderLayout());
        this.add(new ChuongTrinhKhuyenMaiJPanel());
        this.validate();
        this.repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_pnlQuayVeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDonHang;
    private javax.swing.JLabel lblMaChuongTrinhKhuyenMai;
    private javax.swing.JLabel lblQuayVe;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTenChuongTrinhKhuyenMai;
    private javax.swing.JLabel lblThoiGianTao;
    private javax.swing.JLabel lblThongTinMaKhuyenMai2;
    private javax.swing.JLabel lblTitleMaChuongTrinhKhuyenMai;
    private javax.swing.JLabel lblTitleSoLuong;
    private javax.swing.JLabel lblTitleTenChuongTrinhKhuyenMai;
    private javax.swing.JLabel lblTitleThoiGianTao;
    private GUI.Rounded pnlQuayVe;
    private GUI.Rounded pnlThongTin2;
    private javax.swing.JScrollPane scpChiTietKhuyenMai;
    private static javax.swing.JTable tblChiTietKhuyenMai;
    // End of variables declaration//GEN-END:variables
}
