/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.CHITIET.*;
import DTO.AccountDTO;
import DTO.NhanVienDTO;
import GUI.POPUP.DoiMatKhauJFrame;
import GUI.QLNVJPanel;
import static GUI.Sweet.SweetFileChooser.FileExists;
import static GUI.Sweet.SweetFileChooser.PATH_NHANVIEN;
import static GUI.Sweet.SweetImage.readImageFromFilePath;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import quanlycuahanggiay.DateTime;
import static quanlycuahanggiay.quanlycuahanggiay.currentAccount;
import static quanlycuahanggiay.quanlycuahanggiay.currentNhanVien;


/**
 *
 * @author admin
 */
public class CaiDatJPanel extends javax.swing.JPanel {

    public ArrayList<javax.swing.AbstractButton> arrButton = new ArrayList<>();
    public ImageIcon imgAnhDaiDien;
     /**
     * Creates new form ChiTietNhanVienPanel
     */
    public CaiDatJPanel(){
        initComponents();
        
        lblDoiMatKhau.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        pnlQuayVe.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        setData();
    }
    public void setRole(){
        String Role = currentAccount.getRole();
        int i;
       for(i=0;i<Role.length();i++){
           if(Role.codePointAt(i) == 49)
               arrButton.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checked.png")));
           arrButton.get(i).setEnabled(false);
       }
       for(i=i-1;i<arrButton.size();i++){
           String Command = arrButton.get(i).getActionCommand();
           if(Command.equals(currentNhanVien.getGioiTinh())||Command.equals(currentNhanVien.getCaLam()) || Command.equals(currentNhanVien.getTrangThai())){
               arrButton.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checked.png")));
               arrButton.get(i).setSelected(true);
       }arrButton.get(i).setEnabled(false);
       }
    }
    private void setData(){
        if(currentAccount.getRole().toString().equalsIgnoreCase("admin")){
            return;
        }
    lblMaNhanVien.setText(currentNhanVien.getMaNhanVien());
    lblHoTen.setText(currentNhanVien.getHoTen());
    lblNamSinh.setText(currentNhanVien.getNamSinh());
    lblSoDienThoai.setText(currentNhanVien.getSoDienThoai());
    lblDiaChi.setText(currentNhanVien.getDiaChi());
    lblLuong.setText(currentNhanVien.getLuong());
        arrButton.add(cbxTongQuan);
        arrButton.add(cbxDonHang);
        arrButton.add(cbxSanPham);
        arrButton.add(cbxKhachHang);
        arrButton.add(cbxDoanhThu);
        arrButton.add(cbxThongKe);
        arrButton.add(cbxKhuyenMai);
        arrButton.add(cbxNhapHang);
        arrButton.add(cbxQuanLyNhanVien);
        arrButton.add(cbxQuanLyDanhMuc);
        arrButton.add(radCa1);
        arrButton.add(radCa2);
        arrButton.add(radCa3);
        arrButton.add(radConLam);
        arrButton.add(radNghiLam);
        arrButton.add(radNam);
        arrButton.add(radNu);
        setRole();
        if (!FileExists(PATH_NHANVIEN + currentNhanVien.getImgSource())) {
            currentNhanVien.setImgSource("default.jpg");
            Image imageScale = readImageFromFilePath(PATH_NHANVIEN + currentNhanVien.getImgSource(), 180, 240);
            imgAnhDaiDien = new ImageIcon(imageScale);
            lblAnh.setIcon(imgAnhDaiDien);            
        }
        else{
        Image imageScale = readImageFromFilePath(PATH_NHANVIEN + currentNhanVien.getImgSource(), 180, 240);
        imgAnhDaiDien = new ImageIcon(imageScale);
        lblAnh.setIcon(imgAnhDaiDien);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ThemTaiKhoanJPanel = new GUI.Rounded();
        pnlThongTin = new javax.swing.JPanel();
        lblMa = new javax.swing.JLabel();
        lblNam = new javax.swing.JLabel();
        lblTen = new javax.swing.JLabel();
        lblDienThoai = new javax.swing.JLabel();
        lblDienThoai1 = new javax.swing.JLabel();
        lblNgayVL = new javax.swing.JLabel();
        txtGioiTinh = new javax.swing.JLabel();
        radNam = new javax.swing.JRadioButton();
        radNu = new javax.swing.JRadioButton();
        lblTen2 = new javax.swing.JLabel();
        radCa1 = new javax.swing.JRadioButton();
        radCa2 = new javax.swing.JRadioButton();
        radCa3 = new javax.swing.JRadioButton();
        lblNgayVaoLam = new javax.swing.JLabel();
        lblHoTen = new javax.swing.JLabel();
        lblNamSinh = new javax.swing.JLabel();
        lblSoDienThoai = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblDiaChi = new javax.swing.JTextArea();
        lblMaNhanVien = new javax.swing.JLabel();
        lblAnh = new javax.swing.JLabel();
        pnlQuyen1 = new javax.swing.JPanel();
        lblTen1 = new javax.swing.JLabel();
        lblMucLuong = new javax.swing.JLabel();
        radConLam = new javax.swing.JRadioButton();
        radNghiLam = new javax.swing.JRadioButton();
        lblLuong1 = new javax.swing.JLabel();
        lblDoiMatKhau = new javax.swing.JLabel();
        lblLuong = new javax.swing.JLabel();
        pnlQuyen = new javax.swing.JPanel();
        cbxTongQuan = new javax.swing.JCheckBox();
        cbxSanPham = new javax.swing.JCheckBox();
        cbxKhachHang = new javax.swing.JCheckBox();
        cbxDoanhThu = new javax.swing.JCheckBox();
        cbxNhapHang = new javax.swing.JCheckBox();
        cbxDonHang = new javax.swing.JCheckBox();
        cbxThongKe = new javax.swing.JCheckBox();
        cbxQuanLyNhanVien = new javax.swing.JCheckBox();
        cbxQuanLyDanhMuc = new javax.swing.JCheckBox();
        cbxKhuyenMai = new javax.swing.JCheckBox();
        pnlQuayVe = new GUI.Rounded();
        lblQuayVe = new javax.swing.JLabel();

        setBackground(new java.awt.Color(45, 47, 62));

        ThemTaiKhoanJPanel.setBackground(new java.awt.Color(45, 47, 62));
        ThemTaiKhoanJPanel.setForeground(new java.awt.Color(45, 47, 62));
        ThemTaiKhoanJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlThongTin.setBackground(new java.awt.Color(45, 47, 62));
        pnlThongTin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin cá nhân", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlThongTin.setForeground(new java.awt.Color(45, 47, 62));
        pnlThongTin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMa.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblMa.setForeground(new java.awt.Color(255, 255, 255));
        lblMa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMa.setText("Mã nhân viên:");
        pnlThongTin.add(lblMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 24, -1, -1));

        lblNam.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblNam.setForeground(new java.awt.Color(255, 255, 255));
        lblNam.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNam.setText("Năm sinh:");
        pnlThongTin.add(lblNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 183, -1, -1));

        lblTen.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblTen.setForeground(new java.awt.Color(255, 255, 255));
        lblTen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTen.setText("Họ tên:");
        pnlThongTin.add(lblTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 100, -1, -1));

        lblDienThoai.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblDienThoai.setForeground(new java.awt.Color(255, 255, 255));
        lblDienThoai.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDienThoai.setText("Số điện thoại:");
        pnlThongTin.add(lblDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 220, 100, -1));

        lblDienThoai1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblDienThoai1.setForeground(new java.awt.Color(255, 255, 255));
        lblDienThoai1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDienThoai1.setText("Địa chỉ:");
        pnlThongTin.add(lblDienThoai1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        lblNgayVL.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblNgayVL.setForeground(new java.awt.Color(255, 255, 255));
        lblNgayVL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNgayVL.setText("Ngày vào làm:");
        pnlThongTin.add(lblNgayVL, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 62, -1, -1));

        txtGioiTinh.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtGioiTinh.setForeground(new java.awt.Color(255, 255, 255));
        txtGioiTinh.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtGioiTinh.setText("Giới tính:");
        pnlThongTin.add(txtGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 142, -1, -1));

        radNam.setBackground(new java.awt.Color(45, 47, 62));
        radNam.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        radNam.setForeground(new java.awt.Color(255, 255, 255));
        radNam.setText("Nam");
        radNam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N
        pnlThongTin.add(radNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 138, 67, -1));

        radNu.setBackground(new java.awt.Color(45, 47, 62));
        radNu.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        radNu.setForeground(new java.awt.Color(255, 255, 255));
        radNu.setText("Nữ");
        radNu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N
        pnlThongTin.add(radNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 138, -1, -1));

        lblTen2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblTen2.setForeground(new java.awt.Color(255, 255, 255));
        lblTen2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTen2.setText("Ca làm:");
        pnlThongTin.add(lblTen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 333, -1, -1));

        radCa1.setBackground(new java.awt.Color(45, 47, 62));
        radCa1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        radCa1.setForeground(new java.awt.Color(255, 255, 255));
        radCa1.setText("Ca sáng");
        radCa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N
        pnlThongTin.add(radCa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 329, 84, -1));

        radCa2.setBackground(new java.awt.Color(45, 47, 62));
        radCa2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        radCa2.setForeground(new java.awt.Color(255, 255, 255));
        radCa2.setText("Ca chiều");
        radCa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N
        pnlThongTin.add(radCa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 329, 87, -1));

        radCa3.setBackground(new java.awt.Color(45, 47, 62));
        radCa3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        radCa3.setForeground(new java.awt.Color(255, 255, 255));
        radCa3.setText("Ca tối");
        radCa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N
        pnlThongTin.add(radCa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 329, 87, -1));

        lblNgayVaoLam.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblNgayVaoLam.setForeground(new java.awt.Color(255, 255, 255));
        lblNgayVaoLam.setText("30/04/2020");
        pnlThongTin.add(lblNgayVaoLam, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 62, -1, -1));

        lblHoTen.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblHoTen.setForeground(new java.awt.Color(255, 255, 255));
        lblHoTen.setText("Phan Công Sơn");
        pnlThongTin.add(lblHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        lblNamSinh.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblNamSinh.setForeground(new java.awt.Color(255, 255, 255));
        lblNamSinh.setText("2000");
        pnlThongTin.add(lblNamSinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, 20));

        lblSoDienThoai.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblSoDienThoai.setForeground(new java.awt.Color(255, 255, 255));
        lblSoDienThoai.setText("0916375645");
        pnlThongTin.add(lblSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(53, 55, 70));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        lblDiaChi.setBackground(new java.awt.Color(45, 47, 62));
        lblDiaChi.setColumns(20);
        lblDiaChi.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblDiaChi.setForeground(new java.awt.Color(255, 255, 255));
        lblDiaChi.setLineWrap(true);
        lblDiaChi.setRows(5);
        lblDiaChi.setText("120 Công Chúa Ngọc Hân,\nPhường 12,Quận 11, TP Hồ Chí Minh\n");
        lblDiaChi.setBorder(null);
        lblDiaChi.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        lblDiaChi.setEnabled(false);
        jScrollPane1.setViewportView(lblDiaChi);

        pnlThongTin.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 210, 60));

        lblMaNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien.setFont(new java.awt.Font("#9Slide03 Source Sans Pro SemiB", 0, 20)); // NOI18N
        lblMaNhanVien.setForeground(new java.awt.Color(210, 48, 44));
        lblMaNhanVien.setText("NV001");
        pnlThongTin.add(lblMaNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));
        pnlThongTin.add(lblAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 170, 210));

        ThemTaiKhoanJPanel.add(pnlThongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 590, 420));

        pnlQuyen1.setBackground(new java.awt.Color(45, 47, 62));
        pnlQuyen1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tác vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlQuyen1.setForeground(new java.awt.Color(45, 47, 62));

        lblTen1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblTen1.setForeground(new java.awt.Color(255, 255, 255));
        lblTen1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTen1.setText("Trạng thái:");

        lblMucLuong.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblMucLuong.setForeground(new java.awt.Color(255, 255, 255));
        lblMucLuong.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMucLuong.setText("Mức lương:");

        radConLam.setBackground(new java.awt.Color(45, 47, 62));
        radConLam.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        radConLam.setForeground(new java.awt.Color(255, 255, 255));
        radConLam.setText("Còn làm");
        radConLam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N

        radNghiLam.setBackground(new java.awt.Color(45, 47, 62));
        radNghiLam.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        radNghiLam.setForeground(new java.awt.Color(255, 255, 255));
        radNghiLam.setText("Nghỉ làm");
        radNghiLam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N

        lblLuong1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblLuong1.setForeground(new java.awt.Color(255, 255, 255));
        lblLuong1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLuong1.setText("Mật khẩu:");

        lblDoiMatKhau.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblDoiMatKhau.setForeground(new java.awt.Color(210, 57, 44));
        lblDoiMatKhau.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDoiMatKhau.setText("Đổi mật khẩu");
        lblDoiMatKhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(210, 57, 44)));
        lblDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDoiMatKhauMouseClicked(evt);
            }
        });

        lblLuong.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblLuong.setForeground(new java.awt.Color(255, 255, 255));
        lblLuong.setText("20000000");

        javax.swing.GroupLayout pnlQuyen1Layout = new javax.swing.GroupLayout(pnlQuyen1);
        pnlQuyen1.setLayout(pnlQuyen1Layout);
        pnlQuyen1Layout.setHorizontalGroup(
            pnlQuyen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuyen1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlQuyen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlQuyen1Layout.createSequentialGroup()
                        .addGroup(pnlQuyen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTen1)
                            .addComponent(lblMucLuong))
                        .addGroup(pnlQuyen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlQuyen1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radConLam, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radNghiLam))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQuyen1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlQuyen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDoiMatKhau)
                                    .addComponent(lblLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30))
                    .addGroup(pnlQuyen1Layout.createSequentialGroup()
                        .addComponent(lblLuong1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlQuyen1Layout.setVerticalGroup(
            pnlQuyen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuyen1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlQuyen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radNghiLam)
                    .addComponent(radConLam)
                    .addComponent(lblTen1))
                .addGap(18, 18, 18)
                .addGroup(pnlQuyen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMucLuong)
                    .addComponent(lblLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlQuyen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLuong1)
                    .addComponent(lblDoiMatKhau))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ThemTaiKhoanJPanel.add(pnlQuyen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 290, 140));

        pnlQuyen.setBackground(new java.awt.Color(45, 47, 62));
        pnlQuyen.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quyền", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlQuyen.setForeground(new java.awt.Color(45, 47, 62));
        pnlQuyen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxTongQuan.setBackground(new java.awt.Color(45, 47, 62));
        cbxTongQuan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxTongQuan.setForeground(new java.awt.Color(255, 255, 255));
        cbxTongQuan.setText("Tổng quan");
        cbxTongQuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N
        pnlQuyen.add(cbxTongQuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 38, 134, -1));

        cbxSanPham.setBackground(new java.awt.Color(45, 47, 62));
        cbxSanPham.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxSanPham.setForeground(new java.awt.Color(255, 255, 255));
        cbxSanPham.setText("Sản phẩm");
        cbxSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N
        pnlQuyen.add(cbxSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 132, -1));

        cbxKhachHang.setBackground(new java.awt.Color(45, 47, 62));
        cbxKhachHang.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        cbxKhachHang.setText("Khách hàng");
        cbxKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N
        pnlQuyen.add(cbxKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 132, -1));

        cbxDoanhThu.setBackground(new java.awt.Color(45, 47, 62));
        cbxDoanhThu.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxDoanhThu.setForeground(new java.awt.Color(255, 255, 255));
        cbxDoanhThu.setText("Doanh thu");
        cbxDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N
        pnlQuyen.add(cbxDoanhThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 158, 134, -1));

        cbxNhapHang.setBackground(new java.awt.Color(45, 47, 62));
        cbxNhapHang.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxNhapHang.setForeground(new java.awt.Color(255, 255, 255));
        cbxNhapHang.setText("Nhập hàng");
        cbxNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N
        pnlQuyen.add(cbxNhapHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 132, -1));

        cbxDonHang.setBackground(new java.awt.Color(45, 47, 62));
        cbxDonHang.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxDonHang.setForeground(new java.awt.Color(255, 255, 255));
        cbxDonHang.setText("Đơn hàng");
        cbxDonHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N
        pnlQuyen.add(cbxDonHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 78, 134, -1));

        cbxThongKe.setBackground(new java.awt.Color(45, 47, 62));
        cbxThongKe.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxThongKe.setForeground(new java.awt.Color(255, 255, 255));
        cbxThongKe.setText("Thống kê");
        cbxThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N
        pnlQuyen.add(cbxThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 118, 100, -1));

        cbxQuanLyNhanVien.setBackground(new java.awt.Color(45, 47, 62));
        cbxQuanLyNhanVien.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxQuanLyNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        cbxQuanLyNhanVien.setText("Quản lí nhân viên");
        cbxQuanLyNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N
        pnlQuyen.add(cbxQuanLyNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        cbxQuanLyDanhMuc.setBackground(new java.awt.Color(45, 47, 62));
        cbxQuanLyDanhMuc.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxQuanLyDanhMuc.setForeground(new java.awt.Color(255, 255, 255));
        cbxQuanLyDanhMuc.setText("Quản lí danh mục");
        cbxQuanLyDanhMuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N
        cbxQuanLyDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxQuanLyDanhMucActionPerformed(evt);
            }
        });
        pnlQuyen.add(cbxQuanLyDanhMuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 198, -1, -1));

        cbxKhuyenMai.setBackground(new java.awt.Color(45, 47, 62));
        cbxKhuyenMai.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxKhuyenMai.setForeground(new java.awt.Color(255, 255, 255));
        cbxKhuyenMai.setText("Khuyến mãi");
        cbxKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N
        pnlQuyen.add(cbxKhuyenMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 132, -1));

        ThemTaiKhoanJPanel.add(pnlQuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 290, 420));

        pnlQuayVe.setBackground(new java.awt.Color(45, 47, 62));
        pnlQuayVe.setForeground(new java.awt.Color(210, 57, 44));
        pnlQuayVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlQuayVeMouseClicked(evt);
            }
        });

        lblQuayVe.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblQuayVe.setForeground(new java.awt.Color(255, 255, 255));
        lblQuayVe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuayVe.setText("Đăng xuất");

        javax.swing.GroupLayout pnlQuayVeLayout = new javax.swing.GroupLayout(pnlQuayVe);
        pnlQuayVe.setLayout(pnlQuayVeLayout);
        pnlQuayVeLayout.setHorizontalGroup(
            pnlQuayVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuayVeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuayVe, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlQuayVeLayout.setVerticalGroup(
            pnlQuayVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQuayVe, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        ThemTaiKhoanJPanel.add(pnlQuayVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ThemTaiKhoanJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ThemTaiKhoanJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbxQuanLyDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxQuanLyDanhMucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxQuanLyDanhMucActionPerformed

    private void pnlQuayVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQuayVeMouseClicked
        if(SwingUtilities.isLeftMouseButton(evt))
            ((javax.swing.JFrame) SwingUtilities.getWindowAncestor(quanlycuahanggiay.quanlycuahanggiay.bg)).dispose();
            new GUI.LoginJFrame().setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_pnlQuayVeMouseClicked

    private void lblDoiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoiMatKhauMouseClicked
               if (SwingUtilities.isLeftMouseButton(evt))

                       new DoiMatKhauJFrame(lblMaNhanVien.getText()).setVisible(true);

//new DoiMatKhauJFrame(currentNhanVien.getMaNhanVien()).setVisible(true);
    }//GEN-LAST:event_lblDoiMatKhauMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.Rounded ThemTaiKhoanJPanel;
    private javax.swing.JCheckBox cbxDoanhThu;
    private javax.swing.JCheckBox cbxDonHang;
    private javax.swing.JCheckBox cbxKhachHang;
    private javax.swing.JCheckBox cbxKhuyenMai;
    private javax.swing.JCheckBox cbxNhapHang;
    private javax.swing.JCheckBox cbxQuanLyDanhMuc;
    private javax.swing.JCheckBox cbxQuanLyNhanVien;
    private javax.swing.JCheckBox cbxSanPham;
    private javax.swing.JCheckBox cbxThongKe;
    private javax.swing.JCheckBox cbxTongQuan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JTextArea lblDiaChi;
    private javax.swing.JLabel lblDienThoai;
    private javax.swing.JLabel lblDienThoai1;
    private javax.swing.JLabel lblDoiMatKhau;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblLuong;
    private javax.swing.JLabel lblLuong1;
    private javax.swing.JLabel lblMa;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblMucLuong;
    private javax.swing.JLabel lblNam;
    private javax.swing.JLabel lblNamSinh;
    private javax.swing.JLabel lblNgayVL;
    private javax.swing.JLabel lblNgayVaoLam;
    private javax.swing.JLabel lblQuayVe;
    private javax.swing.JLabel lblSoDienThoai;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblTen1;
    private javax.swing.JLabel lblTen2;
    private GUI.Rounded pnlQuayVe;
    private javax.swing.JPanel pnlQuyen;
    private javax.swing.JPanel pnlQuyen1;
    private javax.swing.JPanel pnlThongTin;
    private javax.swing.JRadioButton radCa1;
    private javax.swing.JRadioButton radCa2;
    private javax.swing.JRadioButton radCa3;
    private javax.swing.JRadioButton radConLam;
    private javax.swing.JRadioButton radNam;
    private javax.swing.JRadioButton radNghiLam;
    private javax.swing.JRadioButton radNu;
    private javax.swing.JLabel txtGioiTinh;
    // End of variables declaration//GEN-END:variables
}
