/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.ChiTietDonHangDTO;
import DTO.DonHangDTO;
import DTO.KhachHangDTO;
import DTO.SanPhamDTO;
import GUI.CHITIET.ChiTietDonHangJPanel;
import GUI.Sweet.SweetComboBox;
import GUI.THEMMOI.TaoDonHangJPanel;
import static GUI.TongQuanJPanel.changeColorColumn3;
import static GUI.TongQuanJPanel.changeColorColumn4;
import static GUI.TongQuanJPanel.customTable;
import static GUI.TongQuanJPanel.setJTableColumnsWidth;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import quanlycuahanggiay.DateTime;
import static quanlycuahanggiay.DateTime.TimestampToDateString;

/**
 *
 * @author admin
 */
public class DonHangJPanel extends javax.swing.JPanel {
    Object[] columnNames ={"Mã đơn hàng","Họ tên","Số điện thoại","Ngày lập đơn","Trạng thái"};
    public static KhachHangDTO currentKhachHang;
    public static DonHangDTO currentDonHang;
    public static ArrayList<ChiTietDonHangDTO> currentChiTietDonHangList;
    public static SanPhamDTO currentSanPham;
    static DefaultTableModel listTableModel;
    public ArrayList<DonHangDTO> arraySearch;
    SweetComboBox cbxTrangThai;
    public static ArrayList<ChiTietDonHangDTO> GioHang;
    
    /**
     * Creates new form DonHangJPanel
     */
    /*
    public void setDate(){
        dateTu.setDateFormatString("dd/MM/yyyy");
        dateDen.setDateFormatString("dd/MM/yyyy");
        dateTu.setDate(new Date());
        dateDen.setDate(dateTu.getDate());
        dateDen.setMinSelectableDate(dateTu.getDate());     
        dateNgay.setDateFormatString("dd/MM/yyyy");
        dateNgay.setDate(new Date());

    }  
    */
    public void ShowTable(JTable table,Object[] columnName){
        listTableModel = new DefaultTableModel(columnNames,0);
        table.setDefaultRenderer(Object.class, new RenderTable());
        fetchAll();
    }  
    public void setComboBox(){
        String[] trangthai = {"Tất cả","Hủy","Thành công"};
        cbxTrangThai = new SweetComboBox("#353746","#ffffff",0,0,170,30,trangthai);
        pnlTrangThai.add(cbxTrangThai);   
        cbxTrangThai.addItemListener(new ItemListener(){
            public void itemStateChanged(ItemEvent ie){
                getAdvancedSearch();
            }
        });
        
    }
    
    public void setColor(){
        
        for(int j = 0 ; j<tblDonHang.getRowCount();j++){
            for(int i=4;i<tblDonHang.getColumnCount();i++){
                
                tblDonHang.getColumnModel().getColumn(i).setCellRenderer(new changeColorOfCellTable(tblDonHang,j,i));

            }
            
        }
        
    }
    public DonHangJPanel() {
        initComponents();
        customTable(tblDonHang,scpDonHang);
        ShowTable(tblDonHang,columnNames);
        setJTableColumnsWidth(tblDonHang,tblDonHang.getWidth(),18,28,18,23,13);
        //setDate();
        setColor();
        setComboBox();
        pnlTaoDonHang.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            
        
        
    }
    public static void fetchAll(){
        listTableModel.setRowCount(0);
        quanlycuahanggiay.quanlycuahanggiay.DonHangBUS.DonHangList.forEach(DonHang ->{
            KhachHangDTO KhachHang = quanlycuahanggiay.quanlycuahanggiay.KhachHangBUS.getByMaKhachHang(DonHang.getMaKhachHang());
            Vector row = new Vector();
            row.add(DonHang.getMaDonHang());
            row.add(KhachHang.getHoTen());
            row.add(KhachHang.getSoDienThoai());

            row.add(TimestampToDateString(DonHang.getNgayXuat(),1));
            row.add(getTrangThai(DonHang.getTrangThai()));
            listTableModel.addRow(row);
        });
        tblDonHang.setModel(listTableModel);
    }
    public static String getTrangThai(String MaTrangThai){
        return MaTrangThai.equals("1") ? "Thành Công" : "Hủy";
    }
    public String getGiaTriTrangThai(String currentTrangThai){
        return currentTrangThai.equals("Hủy") ? "0" : "1";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTblDonHangChuaXacNhan = new GUI.Rounded();
        scpDonHang = new javax.swing.JScrollPane();
        tblDonHang = new javax.swing.JTable(){
            public boolean isCellEditable ( int row, int col)
            {
                return false;
            }

        };
        pnlTimKiemHoTenSDT = new GUI.Rounded();
        txtTimKiemHoTenSDT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pnlTimKiemMaDonHang = new GUI.Rounded();
        txtTimKiemMaDonHang = new javax.swing.JTextField();
        pnlTaoDonHang = new GUI.Rounded();
        lblTaoPhieuNhap = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTrangThai = new javax.swing.JLabel();
        pnlTrangThai = new javax.swing.JPanel();

        setBackground(new java.awt.Color(45, 47, 62));
        setPreferredSize(new java.awt.Dimension(920, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTblDonHangChuaXacNhan.setBackground(new java.awt.Color(45, 47, 62));
        pnlTblDonHangChuaXacNhan.setForeground(new java.awt.Color(53, 55, 70));

        scpDonHang.setBackground(new java.awt.Color(53, 55, 70));

        tblDonHang.setAutoCreateRowSorter(true);
        tblDonHang.setBackground(new java.awt.Color(53, 55, 70));
        tblDonHang.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tblDonHang.setForeground(new java.awt.Color(255, 255, 255));
        tblDonHang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblDonHang.setFocusable(false);
        tblDonHang.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblDonHang.setRowHeight(25);
        tblDonHang.setSelectionBackground(new java.awt.Color(72, 74, 89));
        tblDonHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDonHangMouseClicked(evt);
            }
        });
        scpDonHang.setViewportView(tblDonHang);

        javax.swing.GroupLayout pnlTblDonHangChuaXacNhanLayout = new javax.swing.GroupLayout(pnlTblDonHangChuaXacNhan);
        pnlTblDonHangChuaXacNhan.setLayout(pnlTblDonHangChuaXacNhanLayout);
        pnlTblDonHangChuaXacNhanLayout.setHorizontalGroup(
            pnlTblDonHangChuaXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTblDonHangChuaXacNhanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpDonHang, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTblDonHangChuaXacNhanLayout.setVerticalGroup(
            pnlTblDonHangChuaXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTblDonHangChuaXacNhanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(pnlTblDonHangChuaXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 198, 870, 490));

        pnlTimKiemHoTenSDT.setBackground(new java.awt.Color(45, 47, 62));
        pnlTimKiemHoTenSDT.setForeground(new java.awt.Color(62, 64, 78));
        pnlTimKiemHoTenSDT.setFocusable(false);

        txtTimKiemHoTenSDT.setBackground(new java.awt.Color(62, 64, 78));
        txtTimKiemHoTenSDT.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTimKiemHoTenSDT.setForeground(new java.awt.Color(192, 192, 192));
        txtTimKiemHoTenSDT.setBorder(null);
        txtTimKiemHoTenSDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemHoTenSDTKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlTimKiemHoTenSDTLayout = new javax.swing.GroupLayout(pnlTimKiemHoTenSDT);
        pnlTimKiemHoTenSDT.setLayout(pnlTimKiemHoTenSDTLayout);
        pnlTimKiemHoTenSDTLayout.setHorizontalGroup(
            pnlTimKiemHoTenSDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTimKiemHoTenSDTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiemHoTenSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTimKiemHoTenSDTLayout.setVerticalGroup(
            pnlTimKiemHoTenSDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTimKiemHoTenSDTLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimKiemHoTenSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnlTimKiemHoTenSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mã đơn hàng:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 30));

        pnlTimKiemMaDonHang.setBackground(new java.awt.Color(45, 47, 62));
        pnlTimKiemMaDonHang.setForeground(new java.awt.Color(62, 64, 78));
        pnlTimKiemMaDonHang.setFocusable(false);

        txtTimKiemMaDonHang.setBackground(new java.awt.Color(62, 64, 78));
        txtTimKiemMaDonHang.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTimKiemMaDonHang.setForeground(new java.awt.Color(192, 192, 192));
        txtTimKiemMaDonHang.setBorder(null);
        txtTimKiemMaDonHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemMaDonHangKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlTimKiemMaDonHangLayout = new javax.swing.GroupLayout(pnlTimKiemMaDonHang);
        pnlTimKiemMaDonHang.setLayout(pnlTimKiemMaDonHangLayout);
        pnlTimKiemMaDonHangLayout.setHorizontalGroup(
            pnlTimKiemMaDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTimKiemMaDonHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiemMaDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTimKiemMaDonHangLayout.setVerticalGroup(
            pnlTimKiemMaDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTimKiemMaDonHangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimKiemMaDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnlTimKiemMaDonHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        pnlTaoDonHang.setBackground(new java.awt.Color(45, 47, 62));
        pnlTaoDonHang.setForeground(new java.awt.Color(210, 57, 44));
        pnlTaoDonHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTaoDonHangMouseClicked(evt);
            }
        });

        lblTaoPhieuNhap.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblTaoPhieuNhap.setForeground(new java.awt.Color(255, 255, 255));
        lblTaoPhieuNhap.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTaoPhieuNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        lblTaoPhieuNhap.setText("Tạo đơn hàng");

        javax.swing.GroupLayout pnlTaoDonHangLayout = new javax.swing.GroupLayout(pnlTaoDonHang);
        pnlTaoDonHang.setLayout(pnlTaoDonHangLayout);
        pnlTaoDonHangLayout.setHorizontalGroup(
            pnlTaoDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaoDonHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTaoPhieuNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTaoDonHangLayout.setVerticalGroup(
            pnlTaoDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTaoDonHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTaoPhieuNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(pnlTaoDonHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, 160, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Họ tên/Số điện thoại:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 30));

        lblTrangThai.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTrangThai.setForeground(new java.awt.Color(255, 255, 255));
        lblTrangThai.setText("Trạng thái:");
        add(lblTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, -1, 30));

        pnlTrangThai.setBackground(new java.awt.Color(53, 55, 70));

        javax.swing.GroupLayout pnlTrangThaiLayout = new javax.swing.GroupLayout(pnlTrangThai);
        pnlTrangThai.setLayout(pnlTrangThaiLayout);
        pnlTrangThaiLayout.setHorizontalGroup(
            pnlTrangThaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        pnlTrangThaiLayout.setVerticalGroup(
            pnlTrangThaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        add(pnlTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 170, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void tblDonHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDonHangMouseClicked
        int column = tblDonHang.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tblDonHang.getRowHeight();
        if(row < tblDonHang.getRowCount() && row >= 0 && column < tblDonHang.getColumnCount() && column >= 0){
            Object value = tblDonHang.getValueAt(row, column);
            if(value instanceof JLabel){
                JLabel label = (JLabel) value;
                for(int i=0;i<tblDonHang.getColumnCount()-2;i++){
                    System.out.println(tblDonHang.getModel().getValueAt(row,i));
                }
            }
            else if(value instanceof JButton){
                JButton label = (JButton) value;
                for(int i=0;i<tblDonHang.getColumnCount()-2;i++){
                    System.out.println(tblDonHang.getModel().getValueAt(row,i));                
                }
            }
            else {
                    currentDonHang = quanlycuahanggiay.quanlycuahanggiay.DonHangBUS.getByMaDonHang((String) tblDonHang.getModel().getValueAt(row,0));
                    currentKhachHang = quanlycuahanggiay.quanlycuahanggiay.KhachHangBUS.getByMaKhachHang(currentDonHang.getMaKhachHang());
                    currentChiTietDonHangList = quanlycuahanggiay.quanlycuahanggiay.ChiTietDonHangBUS.getList(currentDonHang.getMaDonHang());    
                    this.removeAll();
                    this.setLayout(new BorderLayout());
                    this.add(new ChiTietDonHangJPanel());
                    this.validate();
                    this.repaint();
                }
            

        }
    }//GEN-LAST:event_tblDonHangMouseClicked

    private void pnlTaoDonHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTaoDonHangMouseClicked
            GioHang = new ArrayList<>();
            this.removeAll();
            this.setLayout(new BorderLayout());
            this.add(new TaoDonHangJPanel(true));
            this.validate();
            this.repaint();
    }//GEN-LAST:event_pnlTaoDonHangMouseClicked

    private void txtTimKiemHoTenSDTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemHoTenSDTKeyReleased
        getAdvancedSearch();
    }//GEN-LAST:event_txtTimKiemHoTenSDTKeyReleased

    private void txtTimKiemMaDonHangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemMaDonHangKeyReleased
        getAdvancedSearch();
    }//GEN-LAST:event_txtTimKiemMaDonHangKeyReleased

    private void getAdvancedSearch(){
        HashMap<String,String> advancedSearch = new HashMap<>();
        advancedSearch.put("HoTenSDT",txtTimKiemHoTenSDT.getText());
        advancedSearch.put("MaDonHang",txtTimKiemMaDonHang.getText());
        advancedSearch.put("TrangThai","");  
        if(!cbxTrangThai.getSelectedItem().equals("Tất cả"))
            advancedSearch.replace("TrangThai",getGiaTriTrangThai(cbxTrangThai.getSelectedItem().toString()));
        arraySearch = quanlycuahanggiay.quanlycuahanggiay.DonHangBUS.advancedSearch(advancedSearch);
        search();
    }

    public  void search(){
        listTableModel.setRowCount(0);
        arraySearch.forEach( DonHang ->{
            KhachHangDTO KhachHang = quanlycuahanggiay.quanlycuahanggiay.KhachHangBUS.getByMaKhachHang(DonHang.getMaKhachHang());
            Vector row = new Vector();
            row.add(DonHang.getMaDonHang());
            row.add(KhachHang.getHoTen());
            row.add(KhachHang.getSoDienThoai());
            row.add(DateTime.TimestampToDateString(DonHang.getNgayXuat(),0));
            row.add(getTrangThai(DonHang.getTrangThai()));
            listTableModel.addRow(row);
        });
        tblDonHang.setModel(listTableModel);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblTaoPhieuNhap;
    private javax.swing.JLabel lblTrangThai;
    private GUI.Rounded pnlTaoDonHang;
    private GUI.Rounded pnlTblDonHangChuaXacNhan;
    private GUI.Rounded pnlTimKiemHoTenSDT;
    private GUI.Rounded pnlTimKiemMaDonHang;
    private javax.swing.JPanel pnlTrangThai;
    private javax.swing.JScrollPane scpDonHang;
    private static javax.swing.JTable tblDonHang;
    private javax.swing.JTextField txtTimKiemHoTenSDT;
    private javax.swing.JTextField txtTimKiemMaDonHang;
    // End of variables declaration//GEN-END:variables
}
