/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.KhachHangDTO;
import GUI.CHITIET.ChiTietKhachHangJPanel;
import GUI.Sweet.SweetComboBox;
import static GUI.TongQuanJPanel.customTable;
import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class KhachHangJPanel extends javax.swing.JPanel {
    Object[] columnNames ={"Mã khách hàng","Tên khách hàng","Email","Số điện thoại","Địa chỉ"};
    static DefaultTableModel listTableModel;
    public static KhachHangDTO currentKhachHang;
    public ArrayList<KhachHangDTO> arraySearch;
    
    public void ShowTable(JTable table,Object[] columnName){
        listTableModel = new DefaultTableModel(columnNames,0);
        table.setDefaultRenderer(Object.class, new RenderTable());
        fetchAll();
    }
    /**
     * Creates new form NguoiDungJPanel
     */
    public KhachHangJPanel() {
        initComponents();
        customTable(tblKhachHang,scpKhachHang);
        ShowTable(tblKhachHang,columnNames);
     
    }
    
    public static void fetchAll(){
        listTableModel.setRowCount(0);
        quanlycuahanggiay.quanlycuahanggiay.KhachHangBUS.KhachHangList.forEach(KhachHang ->{
            Vector row = new Vector();
            row.add(KhachHang.getMaKhachHang());
            row.add(KhachHang.getHoTen());
            row.add(KhachHang.getEmail());
            row.add(KhachHang.getSoDienThoai());
            row.add(KhachHang.getDiaChi());
            listTableModel.addRow(row);
        });
        tblKhachHang.setModel(listTableModel);
    }
    
    public void search(){
        if(arraySearch.isEmpty() && (txtTimKiemMaKhachHang.getText().equals("") && txtTimKiemHoTen.getText().equals("") && txtTimKiemEmail.getText().equals("") && txtTimKiemSDT.getText().equals(""))){
            fetchAll(); 
            return;
        }
        listTableModel.setRowCount(0);
        arraySearch.forEach(KhachHang ->{
            Vector row = new Vector();
            row.add(KhachHang.getMaKhachHang());
            row.add(KhachHang.getHoTen());
            row.add(KhachHang.getEmail());
            row.add(KhachHang.getSoDienThoai());
            row.add(KhachHang.getDiaChi());
            listTableModel.addRow(row);
        });
        tblKhachHang.setModel(listTableModel);
    }
    
    private void getAdvancedSearch(){
        HashMap<String,String> advancedSearch = new HashMap<>();
        advancedSearch.put("MaKhachHang", txtTimKiemMaKhachHang.getText());
        advancedSearch.put("HoTen", txtTimKiemHoTen.getText());
        advancedSearch.put("Email",txtTimKiemEmail.getText());
        advancedSearch.put("SoDienThoai", txtTimKiemSDT.getText());
        arraySearch = quanlycuahanggiay.quanlycuahanggiay.KhachHangBUS.advancedSearch(advancedSearch);
        search();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTblDonHangChuaXacNhan = new GUI.Rounded();
        scpKhachHang = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable(){
            public boolean isCellEditable ( int row, int col)
            {
                return false;
            }

        };
        pnlTimKiemSDT = new GUI.Rounded();
        txtTimKiemSDT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlTimKiemHoTen = new GUI.Rounded();
        txtTimKiemHoTen = new javax.swing.JTextField();
        pnlTimKiemMaKhachHang = new GUI.Rounded();
        txtTimKiemMaKhachHang = new javax.swing.JTextField();
        pnlTimKiemEmail = new GUI.Rounded();
        txtTimKiemEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnlNhapExcel = new GUI.Rounded();
        lblTaoPhieuNhap1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(45, 47, 62));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTblDonHangChuaXacNhan.setBackground(new java.awt.Color(45, 47, 62));
        pnlTblDonHangChuaXacNhan.setForeground(new java.awt.Color(53, 55, 70));

        scpKhachHang.setBackground(new java.awt.Color(53, 55, 70));

        tblKhachHang.setAutoCreateRowSorter(true);
        tblKhachHang.setBackground(new java.awt.Color(53, 55, 70));
        tblKhachHang.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tblKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblKhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblKhachHang.setFocusable(false);
        tblKhachHang.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblKhachHang.setRowHeight(25);
        tblKhachHang.setSelectionBackground(new java.awt.Color(72, 74, 89));
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        scpKhachHang.setViewportView(tblKhachHang);

        javax.swing.GroupLayout pnlTblDonHangChuaXacNhanLayout = new javax.swing.GroupLayout(pnlTblDonHangChuaXacNhan);
        pnlTblDonHangChuaXacNhan.setLayout(pnlTblDonHangChuaXacNhanLayout);
        pnlTblDonHangChuaXacNhanLayout.setHorizontalGroup(
            pnlTblDonHangChuaXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTblDonHangChuaXacNhanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTblDonHangChuaXacNhanLayout.setVerticalGroup(
            pnlTblDonHangChuaXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTblDonHangChuaXacNhanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(pnlTblDonHangChuaXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 218, -1, 510));

        pnlTimKiemSDT.setBackground(new java.awt.Color(45, 47, 62));
        pnlTimKiemSDT.setForeground(new java.awt.Color(62, 64, 78));
        pnlTimKiemSDT.setFocusable(false);

        txtTimKiemSDT.setBackground(new java.awt.Color(62, 64, 78));
        txtTimKiemSDT.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTimKiemSDT.setForeground(new java.awt.Color(192, 192, 192));
        txtTimKiemSDT.setBorder(null);
        txtTimKiemSDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemSDTKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlTimKiemSDTLayout = new javax.swing.GroupLayout(pnlTimKiemSDT);
        pnlTimKiemSDT.setLayout(pnlTimKiemSDTLayout);
        pnlTimKiemSDTLayout.setHorizontalGroup(
            pnlTimKiemSDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTimKiemSDTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiemSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTimKiemSDTLayout.setVerticalGroup(
            pnlTimKiemSDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTimKiemSDTLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimKiemSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnlTimKiemSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Số điện thoại:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 30));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tên khách hàng:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 30));

        pnlTimKiemHoTen.setBackground(new java.awt.Color(45, 47, 62));
        pnlTimKiemHoTen.setForeground(new java.awt.Color(62, 64, 78));
        pnlTimKiemHoTen.setFocusable(false);

        txtTimKiemHoTen.setBackground(new java.awt.Color(62, 64, 78));
        txtTimKiemHoTen.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTimKiemHoTen.setForeground(new java.awt.Color(192, 192, 192));
        txtTimKiemHoTen.setBorder(null);
        txtTimKiemHoTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemHoTenKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlTimKiemHoTenLayout = new javax.swing.GroupLayout(pnlTimKiemHoTen);
        pnlTimKiemHoTen.setLayout(pnlTimKiemHoTenLayout);
        pnlTimKiemHoTenLayout.setHorizontalGroup(
            pnlTimKiemHoTenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTimKiemHoTenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiemHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTimKiemHoTenLayout.setVerticalGroup(
            pnlTimKiemHoTenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTimKiemHoTenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimKiemHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnlTimKiemHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        pnlTimKiemMaKhachHang.setBackground(new java.awt.Color(45, 47, 62));
        pnlTimKiemMaKhachHang.setForeground(new java.awt.Color(62, 64, 78));
        pnlTimKiemMaKhachHang.setFocusable(false);

        txtTimKiemMaKhachHang.setBackground(new java.awt.Color(62, 64, 78));
        txtTimKiemMaKhachHang.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTimKiemMaKhachHang.setForeground(new java.awt.Color(192, 192, 192));
        txtTimKiemMaKhachHang.setBorder(null);
        txtTimKiemMaKhachHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemMaKhachHangKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlTimKiemMaKhachHangLayout = new javax.swing.GroupLayout(pnlTimKiemMaKhachHang);
        pnlTimKiemMaKhachHang.setLayout(pnlTimKiemMaKhachHangLayout);
        pnlTimKiemMaKhachHangLayout.setHorizontalGroup(
            pnlTimKiemMaKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTimKiemMaKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiemMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTimKiemMaKhachHangLayout.setVerticalGroup(
            pnlTimKiemMaKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTimKiemMaKhachHangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimKiemMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnlTimKiemMaKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        pnlTimKiemEmail.setBackground(new java.awt.Color(45, 47, 62));
        pnlTimKiemEmail.setForeground(new java.awt.Color(62, 64, 78));
        pnlTimKiemEmail.setFocusable(false);

        txtTimKiemEmail.setBackground(new java.awt.Color(62, 64, 78));
        txtTimKiemEmail.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTimKiemEmail.setForeground(new java.awt.Color(192, 192, 192));
        txtTimKiemEmail.setBorder(null);
        txtTimKiemEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemEmailKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlTimKiemEmailLayout = new javax.swing.GroupLayout(pnlTimKiemEmail);
        pnlTimKiemEmail.setLayout(pnlTimKiemEmailLayout);
        pnlTimKiemEmailLayout.setHorizontalGroup(
            pnlTimKiemEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTimKiemEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiemEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTimKiemEmailLayout.setVerticalGroup(
            pnlTimKiemEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTimKiemEmailLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimKiemEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnlTimKiemEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mã khách hàng:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 30));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 30));

        pnlNhapExcel.setBackground(new java.awt.Color(45, 47, 62));
        pnlNhapExcel.setForeground(new java.awt.Color(210, 57, 44));
        pnlNhapExcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlNhapExcelMouseClicked(evt);
            }
        });

        lblTaoPhieuNhap1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblTaoPhieuNhap1.setForeground(new java.awt.Color(255, 255, 255));
        lblTaoPhieuNhap1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTaoPhieuNhap1.setText("Nhập Excel");

        javax.swing.GroupLayout pnlNhapExcelLayout = new javax.swing.GroupLayout(pnlNhapExcel);
        pnlNhapExcel.setLayout(pnlNhapExcelLayout);
        pnlNhapExcelLayout.setHorizontalGroup(
            pnlNhapExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNhapExcelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTaoPhieuNhap1)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlNhapExcelLayout.setVerticalGroup(
            pnlNhapExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTaoPhieuNhap1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(pnlNhapExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 130, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        int column = tblKhachHang.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tblKhachHang.getRowHeight();
        
        if(row < tblKhachHang.getRowCount() && row >= 0 && column < tblKhachHang.getColumnCount() && column >= 0){
            this.removeAll();
                    this.setLayout(new BorderLayout());
                    currentKhachHang = quanlycuahanggiay.quanlycuahanggiay.KhachHangBUS.getByMaKhachHang(tblKhachHang.getModel().getValueAt(row, 0).toString());
                    this.add(new ChiTietKhachHangJPanel());
                    this.validate();
                    this.repaint();
            }

        
    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void txtTimKiemHoTenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemHoTenKeyReleased
        getAdvancedSearch();
    }//GEN-LAST:event_txtTimKiemHoTenKeyReleased

    private void txtTimKiemMaKhachHangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemMaKhachHangKeyReleased
        getAdvancedSearch();
    }//GEN-LAST:event_txtTimKiemMaKhachHangKeyReleased

    private void txtTimKiemEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemEmailKeyReleased
        getAdvancedSearch();
    }//GEN-LAST:event_txtTimKiemEmailKeyReleased

    private void txtTimKiemSDTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemSDTKeyReleased
        getAdvancedSearch();
    }//GEN-LAST:event_txtTimKiemSDTKeyReleased

    private void pnlNhapExcelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhapExcelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlNhapExcelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblTaoPhieuNhap1;
    private GUI.Rounded pnlNhapExcel;
    private GUI.Rounded pnlTblDonHangChuaXacNhan;
    private GUI.Rounded pnlTimKiemEmail;
    private GUI.Rounded pnlTimKiemHoTen;
    private GUI.Rounded pnlTimKiemMaKhachHang;
    private GUI.Rounded pnlTimKiemSDT;
    private javax.swing.JScrollPane scpKhachHang;
    private static javax.swing.JTable tblKhachHang;
    private javax.swing.JTextField txtTimKiemEmail;
    private javax.swing.JTextField txtTimKiemHoTen;
    private javax.swing.JTextField txtTimKiemMaKhachHang;
    private javax.swing.JTextField txtTimKiemSDT;
    // End of variables declaration//GEN-END:variables
}
