/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;



import GUI.KHUYENMAI.ChiTietKhuyenMaiJPanel;
import GUI.KHUYENMAI.ChuongTrinhKhuyenMaiJPanel;
import GUI.THEMMOI.TaoMaKhuyenMaiJPanel;
import static GUI.TongQuanJPanel.customTable;
import static GUI.TongQuanJPanel.setJTableColumnsWidth;
import java.awt.BorderLayout;
import java.awt.Cursor;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class KhuyenMaiJPanel extends javax.swing.JPanel {
    Object[] columnNames ={"Mã CTKM","Mã khuyến mãi","Số lượng","Đã dùng","Còn lại","Ngày tạo","Ngày bắt đầu"};
    
    /**
     * Creates new form KhuyenMaiJPanel
     */
    public void ShowTable(JTable table,Object[] columnName){
        
        table.setDefaultRenderer(Object.class, new RenderTable());
        
        Object columnNames[] = columnName;
        DefaultTableModel listTableModel = new DefaultTableModel(columnNames,0);
        Object machuongtrinhkhuyenmai[] = {1,2,3,4,5};
        Object makhuyenmai[] ={"MAGIAMGIA2020","MAGIAMGIA0105","MAGIAMGIA20","MAGIAMGIA2","MAGIAMGIA1"};
        Object ngaytao[] ={"01/05/2000","01/05/2000","01/05/2000","01/05/2000","01/05/2000"};
        Object ngaysudung[] ={"01/05/2000","01/05/2000","01/05/2000","01/05/2000","01/05/2000"};
        Object soluong[] = {500,200,100,500,300};
        Object dadung[] = {200,200,100,100,150};
        Object conlai[] = {300,0,0,400,150};
        Object manhanvien[] = {"NV001","NV001","NV001","NV001","NV001"};
        for(int i=0 ; i<machuongtrinhkhuyenmai.length ; i++){
                Object row[] = {machuongtrinhkhuyenmai[i],makhuyenmai[i],soluong[i],dadung[i],conlai[i],ngaytao[i],ngaysudung[i]};
                listTableModel.addRow(row);
            }
        
        table.setModel(listTableModel);

       
        
    }     
    public KhuyenMaiJPanel() {
        initComponents();
        pnlChuongTrinhKhuyenMai.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        pnlChiTietKhuyenMai.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlChiTietKhuyenMai = new GUI.Rounded();
        imgKhuyenMai = new javax.swing.JLabel();
        lblKhuyenMai = new javax.swing.JLabel();
        lblTitleKhuyenMai = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlChuongTrinhKhuyenMai = new GUI.Rounded();
        imgKhuyenMai1 = new javax.swing.JLabel();
        lblKhuyenMai1 = new javax.swing.JLabel();
        lblTitleKhuyenMai1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(45, 47, 62));

        pnlChiTietKhuyenMai.setBackground(new java.awt.Color(45, 47, 62));
        pnlChiTietKhuyenMai.setForeground(new java.awt.Color(52, 54, 67));
        pnlChiTietKhuyenMai.setPreferredSize(new java.awt.Dimension(407, 302));
        pnlChiTietKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlChiTietKhuyenMaiMouseClicked(evt);
            }
        });

        imgKhuyenMai.setBackground(new java.awt.Color(52, 54, 67));
        imgKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/khuyenmai.png"))); // NOI18N
        imgKhuyenMai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 54, 67)));

        lblKhuyenMai.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblKhuyenMai.setForeground(new java.awt.Color(255, 255, 255));
        lblKhuyenMai.setText("Chi tiết khuyến mãi");

        lblTitleKhuyenMai.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lblTitleKhuyenMai.setForeground(new java.awt.Color(192, 192, 192));
        lblTitleKhuyenMai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleKhuyenMai.setText("Khuyến mãi");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow-right.png"))); // NOI18N

        javax.swing.GroupLayout pnlChiTietKhuyenMaiLayout = new javax.swing.GroupLayout(pnlChiTietKhuyenMai);
        pnlChiTietKhuyenMai.setLayout(pnlChiTietKhuyenMaiLayout);
        pnlChiTietKhuyenMaiLayout.setHorizontalGroup(
            pnlChiTietKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgKhuyenMai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlChiTietKhuyenMaiLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlChiTietKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitleKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlChiTietKhuyenMaiLayout.createSequentialGroup()
                        .addComponent(lblKhuyenMai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        pnlChiTietKhuyenMaiLayout.setVerticalGroup(
            pnlChiTietKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChiTietKhuyenMaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitleKhuyenMai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlChiTietKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22))
        );

        pnlChuongTrinhKhuyenMai.setBackground(new java.awt.Color(45, 47, 62));
        pnlChuongTrinhKhuyenMai.setForeground(new java.awt.Color(52, 54, 67));
        pnlChuongTrinhKhuyenMai.setPreferredSize(new java.awt.Dimension(407, 302));
        pnlChuongTrinhKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlChuongTrinhKhuyenMaiMouseClicked(evt);
            }
        });

        imgKhuyenMai1.setBackground(new java.awt.Color(52, 54, 67));
        imgKhuyenMai1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgKhuyenMai1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chuongtrinhkhuyenmai.png"))); // NOI18N
        imgKhuyenMai1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 54, 67)));

        lblKhuyenMai1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblKhuyenMai1.setForeground(new java.awt.Color(255, 255, 255));
        lblKhuyenMai1.setText("Chương trình khuyến mãi");

        lblTitleKhuyenMai1.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lblTitleKhuyenMai1.setForeground(new java.awt.Color(192, 192, 192));
        lblTitleKhuyenMai1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleKhuyenMai1.setText("Khuyến mãi");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow-right.png"))); // NOI18N

        javax.swing.GroupLayout pnlChuongTrinhKhuyenMaiLayout = new javax.swing.GroupLayout(pnlChuongTrinhKhuyenMai);
        pnlChuongTrinhKhuyenMai.setLayout(pnlChuongTrinhKhuyenMaiLayout);
        pnlChuongTrinhKhuyenMaiLayout.setHorizontalGroup(
            pnlChuongTrinhKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChuongTrinhKhuyenMaiLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlChuongTrinhKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitleKhuyenMai1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKhuyenMai1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
            .addGroup(pnlChuongTrinhKhuyenMaiLayout.createSequentialGroup()
                .addComponent(imgKhuyenMai1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        pnlChuongTrinhKhuyenMaiLayout.setVerticalGroup(
            pnlChuongTrinhKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChuongTrinhKhuyenMaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgKhuyenMai1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlChuongTrinhKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlChuongTrinhKhuyenMaiLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTitleKhuyenMai1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblKhuyenMai1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(pnlChuongTrinhKhuyenMaiLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(pnlChuongTrinhKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(pnlChiTietKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlChuongTrinhKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                    .addComponent(pnlChiTietKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE))
                .addGap(424, 424, 424))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pnlChiTietKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlChiTietKhuyenMaiMouseClicked
        this.removeAll();
        this.setLayout(new BorderLayout());
        this.add(new ChiTietKhuyenMaiJPanel());
        this.validate();
        this.repaint();           // TODO add your handling code here:
    }//GEN-LAST:event_pnlChiTietKhuyenMaiMouseClicked

    private void pnlChuongTrinhKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlChuongTrinhKhuyenMaiMouseClicked
        this.removeAll();
        this.setLayout(new BorderLayout());
        this.add(new ChuongTrinhKhuyenMaiJPanel());
        this.validate();
        this.repaint();   
    }//GEN-LAST:event_pnlChuongTrinhKhuyenMaiMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgKhuyenMai;
    private javax.swing.JLabel imgKhuyenMai1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblKhuyenMai;
    private javax.swing.JLabel lblKhuyenMai1;
    private javax.swing.JLabel lblTitleKhuyenMai;
    private javax.swing.JLabel lblTitleKhuyenMai1;
    private GUI.Rounded pnlChiTietKhuyenMai;
    private GUI.Rounded pnlChuongTrinhKhuyenMai;
    // End of variables declaration//GEN-END:variables
}
