package GUI;

import DTO.PhieuNhapDTO;
import GUI.CHITIET.ChiTietPhieuNhapJPanel;
import GUI.THEMMOI.TaoPhieuNhapJPanel;
import static GUI.TongQuanJPanel.changeColorColumn4;
import static GUI.TongQuanJPanel.customTable;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import static quanlycuahanggiay.Currency.changeCurrency;
import quanlycuahanggiay.DateTime;
import static quanlycuahanggiay.Currency.changeCurrency;

public class PhieuNhapHangJPanel extends javax.swing.JPanel {
    Object[] columnNames ={"Mã phiếu nhập","Mã nhân viên tạo phiếu","Mã nhà cung cấp","Ngày xuất","Tổng tiền"};
    static DefaultTableModel listTableModel;
    public static PhieuNhapDTO currentPhieuNhap;
    public ArrayList<PhieuNhapDTO> arraySearch;

    public void ShowTable(JTable table,Object[] columnName){
        listTableModel = new DefaultTableModel(columnNames,0);
        table.setDefaultRenderer(Object.class, new RenderTable());
        fetchAll(); 
    }  
    public static void fetchAll(){        
        listTableModel.setRowCount(0);
        quanlycuahanggiay.quanlycuahanggiay.PhieuNhapBUS.PhieuNhapList.forEach(PhieuNhap ->{
            Vector row = new Vector();
            row.add(PhieuNhap.getMaPhieuNhap());
            row.add(PhieuNhap.getMaNhanVien());
            row.add(PhieuNhap.getMaNhaCungCap());
            row.add(DateTime.TimestampToDateString(PhieuNhap.getNgayNhap(),1));

            row.add(changeCurrency(PhieuNhap.getTongTien()));

            row.add(changeCurrency(PhieuNhap.getTongTien())+"đ");
            listTableModel.addRow(row);
        });
        tblPhieuNhapHang.setModel(listTableModel);
    }  
    public PhieuNhapHangJPanel() {
        initComponents();
        customTable(tblPhieuNhapHang,scpPhieuNhapHang);
        ShowTable(tblPhieuNhapHang,columnNames);
        changeColorColumn4(tblPhieuNhapHang,Color.red);
        pnlTaoPhieuNhap.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        ((DefaultTableCellRenderer) tblPhieuNhapHang.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(SwingConstants.CENTER);        
    }
    public  void search(){
        if(arraySearch.isEmpty() && (txtTimKiemMaPhieuNhap.getText().equals("")&&txtTimKiemNhanVienTaoPhieu.getText().equals(""))){ fetchAll(); return;}
            
        listTableModel.setRowCount(0);
        arraySearch.forEach( PhieuNhap ->{
            Vector row = new Vector();
            row.add(PhieuNhap.getMaPhieuNhap());
            row.add(PhieuNhap.getMaNhanVien());
            row.add(PhieuNhap.getMaNhaCungCap());
            row.add(PhieuNhap.getNgayNhap());
            row.add(changeCurrency(PhieuNhap.getTongTien()));
            listTableModel.addRow(row);
        });
        tblPhieuNhapHang.setModel(listTableModel);
    }
        private void getAdvancedSearch(){
        HashMap<String,String> advancedSearch = new HashMap<>();
        advancedSearch.put("MaPhieuNhap",txtTimKiemMaPhieuNhap.getText());
        advancedSearch.put("MaNhanVien",txtTimKiemNhanVienTaoPhieu.getText());
        advancedSearch.put("NgayCuThe","");
        advancedSearch.put("TuNgay","");
        advancedSearch.put("DenNgay","");
        arraySearch = quanlycuahanggiay.quanlycuahanggiay.PhieuNhapBUS.advancedSearch(advancedSearch);
        search();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTblPhieuNhapHang = new GUI.Rounded();
        scpPhieuNhapHang = new javax.swing.JScrollPane();
        tblPhieuNhapHang = new javax.swing.JTable(){
            public boolean isCellEditable ( int row, int col)
            {
                return false;
            }

        };
        pnlTaoPhieuNhap = new GUI.Rounded();
        lblTaoPhieuNhap = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTitleMaChiTiet = new javax.swing.JLabel();
        pnlTimKiemNhanVienTaoPhieu = new GUI.Rounded();
        txtTimKiemNhanVienTaoPhieu = new javax.swing.JTextField();
        pnlTimKiemMaPhieuNhap = new GUI.Rounded();
        txtTimKiemMaPhieuNhap = new javax.swing.JTextField();

        setBackground(new java.awt.Color(45, 47, 62));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTblPhieuNhapHang.setBackground(new java.awt.Color(45, 47, 62));
        pnlTblPhieuNhapHang.setForeground(new java.awt.Color(53, 55, 70));

        scpPhieuNhapHang.setBackground(new java.awt.Color(53, 55, 70));

        tblPhieuNhapHang.setAutoCreateRowSorter(true);
        tblPhieuNhapHang.setBackground(new java.awt.Color(53, 55, 70));
        tblPhieuNhapHang.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tblPhieuNhapHang.setForeground(new java.awt.Color(255, 255, 255));
        tblPhieuNhapHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblPhieuNhapHang.setFocusable(false);
        tblPhieuNhapHang.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblPhieuNhapHang.setRowHeight(25);
        tblPhieuNhapHang.setSelectionBackground(new java.awt.Color(72, 74, 89));
        tblPhieuNhapHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhieuNhapHangMouseClicked(evt);
            }
        });
        scpPhieuNhapHang.setViewportView(tblPhieuNhapHang);

        javax.swing.GroupLayout pnlTblPhieuNhapHangLayout = new javax.swing.GroupLayout(pnlTblPhieuNhapHang);
        pnlTblPhieuNhapHang.setLayout(pnlTblPhieuNhapHangLayout);
        pnlTblPhieuNhapHangLayout.setHorizontalGroup(
            pnlTblPhieuNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTblPhieuNhapHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpPhieuNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTblPhieuNhapHangLayout.setVerticalGroup(
            pnlTblPhieuNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTblPhieuNhapHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpPhieuNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(pnlTblPhieuNhapHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 840, 570));

        pnlTaoPhieuNhap.setBackground(new java.awt.Color(45, 47, 62));
        pnlTaoPhieuNhap.setForeground(new java.awt.Color(210, 57, 44));
        pnlTaoPhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTaoPhieuNhapMouseClicked(evt);
            }
        });

        lblTaoPhieuNhap.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblTaoPhieuNhap.setForeground(new java.awt.Color(255, 255, 255));
        lblTaoPhieuNhap.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTaoPhieuNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        lblTaoPhieuNhap.setText("Tạo phiếu nhập");

        javax.swing.GroupLayout pnlTaoPhieuNhapLayout = new javax.swing.GroupLayout(pnlTaoPhieuNhap);
        pnlTaoPhieuNhap.setLayout(pnlTaoPhieuNhapLayout);
        pnlTaoPhieuNhapLayout.setHorizontalGroup(
            pnlTaoPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaoPhieuNhapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTaoPhieuNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTaoPhieuNhapLayout.setVerticalGroup(
            pnlTaoPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTaoPhieuNhapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTaoPhieuNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(pnlTaoPhieuNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mã phiếu nhập:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, 40));

        lblTitleMaChiTiet.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTitleMaChiTiet.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleMaChiTiet.setText("Nhân viên tạo phiếu:");
        add(lblTitleMaChiTiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 40));

        pnlTimKiemNhanVienTaoPhieu.setBackground(new java.awt.Color(45, 47, 62));
        pnlTimKiemNhanVienTaoPhieu.setForeground(new java.awt.Color(62, 64, 78));
        pnlTimKiemNhanVienTaoPhieu.setFocusable(false);

        txtTimKiemNhanVienTaoPhieu.setBackground(new java.awt.Color(62, 64, 78));
        txtTimKiemNhanVienTaoPhieu.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTimKiemNhanVienTaoPhieu.setForeground(new java.awt.Color(192, 192, 192));
        txtTimKiemNhanVienTaoPhieu.setBorder(null);
        txtTimKiemNhanVienTaoPhieu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemNhanVienTaoPhieuKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlTimKiemNhanVienTaoPhieuLayout = new javax.swing.GroupLayout(pnlTimKiemNhanVienTaoPhieu);
        pnlTimKiemNhanVienTaoPhieu.setLayout(pnlTimKiemNhanVienTaoPhieuLayout);
        pnlTimKiemNhanVienTaoPhieuLayout.setHorizontalGroup(
            pnlTimKiemNhanVienTaoPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTimKiemNhanVienTaoPhieuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiemNhanVienTaoPhieu, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
        );
        pnlTimKiemNhanVienTaoPhieuLayout.setVerticalGroup(
            pnlTimKiemNhanVienTaoPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTimKiemNhanVienTaoPhieuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimKiemNhanVienTaoPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnlTimKiemNhanVienTaoPhieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 470, 40));

        pnlTimKiemMaPhieuNhap.setBackground(new java.awt.Color(45, 47, 62));
        pnlTimKiemMaPhieuNhap.setForeground(new java.awt.Color(62, 64, 78));
        pnlTimKiemMaPhieuNhap.setFocusable(false);

        txtTimKiemMaPhieuNhap.setBackground(new java.awt.Color(62, 64, 78));
        txtTimKiemMaPhieuNhap.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTimKiemMaPhieuNhap.setForeground(new java.awt.Color(192, 192, 192));
        txtTimKiemMaPhieuNhap.setBorder(null);
        txtTimKiemMaPhieuNhap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemMaPhieuNhapKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlTimKiemMaPhieuNhapLayout = new javax.swing.GroupLayout(pnlTimKiemMaPhieuNhap);
        pnlTimKiemMaPhieuNhap.setLayout(pnlTimKiemMaPhieuNhapLayout);
        pnlTimKiemMaPhieuNhapLayout.setHorizontalGroup(
            pnlTimKiemMaPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTimKiemMaPhieuNhapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiemMaPhieuNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTimKiemMaPhieuNhapLayout.setVerticalGroup(
            pnlTimKiemMaPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTimKiemMaPhieuNhapLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimKiemMaPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnlTimKiemMaPhieuNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 470, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tblPhieuNhapHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhieuNhapHangMouseClicked
        int column = tblPhieuNhapHang.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tblPhieuNhapHang.getRowHeight();
        if(row < tblPhieuNhapHang.getRowCount() && row >= 0 && column < tblPhieuNhapHang.getColumnCount() && column >= 0){
                    currentPhieuNhap = quanlycuahanggiay.quanlycuahanggiay.PhieuNhapBUS.getByMaPhieuNhap((String) tblPhieuNhapHang.getModel().getValueAt(row,0));
                    this.removeAll();
                    this.setLayout(new BorderLayout());
                    this.add(new ChiTietPhieuNhapJPanel(currentPhieuNhap));
                    this.validate();
                    this.repaint();
                }

    }//GEN-LAST:event_tblPhieuNhapHangMouseClicked

    private void pnlTaoPhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTaoPhieuNhapMouseClicked
                    this.removeAll();
                    this.setLayout(new BorderLayout());
                    this.add(new TaoPhieuNhapJPanel());
                    this.validate();
                    this.repaint();        
    }//GEN-LAST:event_pnlTaoPhieuNhapMouseClicked

    private void txtTimKiemMaPhieuNhapKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemMaPhieuNhapKeyReleased
        getAdvancedSearch();
    }//GEN-LAST:event_txtTimKiemMaPhieuNhapKeyReleased

    private void txtTimKiemNhanVienTaoPhieuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemNhanVienTaoPhieuKeyReleased
        getAdvancedSearch();
    }//GEN-LAST:event_txtTimKiemNhanVienTaoPhieuKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblTaoPhieuNhap;
    private javax.swing.JLabel lblTitleMaChiTiet;
    private GUI.Rounded pnlTaoPhieuNhap;
    private GUI.Rounded pnlTblPhieuNhapHang;
    private GUI.Rounded pnlTimKiemMaPhieuNhap;
    private GUI.Rounded pnlTimKiemNhanVienTaoPhieu;
    private javax.swing.JScrollPane scpPhieuNhapHang;
    private static javax.swing.JTable tblPhieuNhapHang;
    private javax.swing.JTextField txtTimKiemMaPhieuNhap;
    private javax.swing.JTextField txtTimKiemNhanVienTaoPhieu;
    // End of variables declaration//GEN-END:variables
}
