/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static quanlycuahanggiay.Regexp.*;
import DTO.AccountDTO;
import DTO.NhanVienDTO;
import static GUI.CHITIET.ChiTietNhanVienJPanel.currentNhanVien;
import static GUI.Sweet.SweetFileChooser.ImageFileChooser;
import static GUI.Sweet.SweetFileChooser.PATH_NHANVIEN;
import static GUI.Sweet.SweetImage.readImageFromFile;
import static GUI.Sweet.SweetImage.readImageFromFilePath;
import static GUI.Sweet.SweetImage.resizeImage;
import static GUI.Sweet.SweetImage.saveImage;
import java.awt.Cursor;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.io.IOException;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import quanlycuahanggiay.DateTime;

/**
 *
 * @author Administrator
 */
public class ThemTaiKhoanJPanel extends javax.swing.JPanel {

    public ArrayList<javax.swing.AbstractButton> arrButton = new ArrayList<>();
    public NhanVienDTO NhanVien;
    public AccountDTO Account;

    /**
     * Creates new form NewJPanel
     */
    public ThemTaiKhoanJPanel() {
        initComponents();
        initEvent();
        lblNgayVaoLam.setText(quanlycuahanggiay.DateTime.getCurrenDateString(1));
        lblMaNhanVien.setText(quanlycuahanggiay.quanlycuahanggiay.NhanVienBUS.getLatest());
        lblAnh.setIcon(readImageFromFile(PATH_NHANVIEN + "default.jpg", 168, 238));
    
    }

    public void initEvent() {
        arrButton.add(cbxTongQuan);
        arrButton.add(cbxDonHang);
        arrButton.add(cbxSanPham);
        arrButton.add(cbxKhachHang);
        arrButton.add(cbxDoanhThu);
        arrButton.add(cbxThongKe);
        arrButton.add(cbxKhuyenMai);
        arrButton.add(cbxNhapHang);
        arrButton.add(cbxQuanLyNhanVien);
        arrButton.add(cbxQuanLyDanhMuc);
        arrButton.add(radCa1);
        arrButton.add(radCa2);
        arrButton.add(radCa3);
        arrButton.add(radConLam);
        arrButton.add(radNghiLam);
        arrButton.add(radNam);
        arrButton.add(radNu);
        for (javax.swing.AbstractButton checkbox : arrButton) {
            checkbox.setActionCommand(checkbox.getText());
            checkbox.addItemListener(new ItemListener() {
                @Override
                public void itemStateChanged(ItemEvent ie) {
                    javax.swing.AbstractButton currentItem = (javax.swing.AbstractButton) ie.getItem();
                    if (ie.getStateChange() == 1) {
                        currentItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checked.png")));
                    } else {
                        currentItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png")));
                    }
                }
            });
        }

        radNam.setSelected(true);
        radCa1.setSelected(true);
        radConLam.setSelected(true);
        arrButton.remove(radCa1);
        arrButton.remove(radCa2);
        arrButton.remove(radCa3);
        arrButton.remove(radConLam);
        arrButton.remove(radNghiLam);
        arrButton.remove(radNam);
        arrButton.remove(radNu);
    }

    public String getRole() {
        String Role = "";
        for (javax.swing.AbstractButton item : arrButton) {
            if (item.isSelected()) {
                Role += "1";
            } else {
                Role += "0";
            }
        }
        return Role += "01";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupGioiTinh = new javax.swing.ButtonGroup();
        groupTrangThai = new javax.swing.ButtonGroup();
        groupCaLam = new javax.swing.ButtonGroup();
        ThemTaiKhoanJPanel = new GUI.Rounded();
        pnlThongTin = new javax.swing.JPanel();
        lblMa = new javax.swing.JLabel();
        lblNam = new javax.swing.JLabel();
        lblTen = new javax.swing.JLabel();
        lblDienThoai = new javax.swing.JLabel();
        lblDienThoai1 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtNamSinh = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        lblNgayVL = new javax.swing.JLabel();
        lblNgayVaoLam = new javax.swing.JLabel();
        txtGioiTinh = new javax.swing.JLabel();
        radNam = new javax.swing.JRadioButton();
        radNu = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextArea();
        lblAddImage = new javax.swing.JLabel();
        lblTen2 = new javax.swing.JLabel();
        radCa1 = new javax.swing.JRadioButton();
        radCa2 = new javax.swing.JRadioButton();
        radCa3 = new javax.swing.JRadioButton();
        lblMaNhanVien = new javax.swing.JLabel();
        lblAnh = new javax.swing.JLabel();
        rounded1 = new GUI.Rounded();
        lblThem = new javax.swing.JLabel();
        pnlQuyen1 = new javax.swing.JPanel();
        lblTen1 = new javax.swing.JLabel();
        txtLuong = new javax.swing.JTextField();
        lblLuong = new javax.swing.JLabel();
        radConLam = new javax.swing.JRadioButton();
        radNghiLam = new javax.swing.JRadioButton();
        pnlQuyen = new javax.swing.JPanel();
        cbxTongQuan = new javax.swing.JCheckBox();
        cbxSanPham = new javax.swing.JCheckBox();
        cbxKhuyenMai = new javax.swing.JCheckBox();
        cbxDoanhThu = new javax.swing.JCheckBox();
        cbxNhapHang = new javax.swing.JCheckBox();
        cbxDonHang = new javax.swing.JCheckBox();
        cbxThongKe = new javax.swing.JCheckBox();
        cbxQuanLyNhanVien = new javax.swing.JCheckBox();
        cbxQuanLyDanhMuc = new javax.swing.JCheckBox();
        cbxKhachHang = new javax.swing.JCheckBox();
        rounded2 = new GUI.Rounded();
        lblNhapLai = new javax.swing.JLabel();

        groupGioiTinh.add(radNam);
        groupGioiTinh.add(radNu);

        groupTrangThai.add(radConLam);
        groupTrangThai.add(radNghiLam);

        groupCaLam.add(radCa1);
        groupCaLam.add(radCa2);
        groupCaLam.add(radCa3);

        setBackground(new java.awt.Color(45, 47, 62));
        setPreferredSize(new java.awt.Dimension(920, 751));

        ThemTaiKhoanJPanel.setBackground(new java.awt.Color(45, 47, 62));
        ThemTaiKhoanJPanel.setForeground(new java.awt.Color(53, 55, 70));
        ThemTaiKhoanJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlThongTin.setBackground(new java.awt.Color(53, 55, 70));
        pnlThongTin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin cá nhân", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlThongTin.setForeground(new java.awt.Color(255, 255, 255));

        lblMa.setFont(new java.awt.Font("#9Slide03 Source Sans Pro Light", 0, 15)); // NOI18N
        lblMa.setForeground(new java.awt.Color(255, 255, 255));
        lblMa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMa.setText("Mã nhân viên");

        lblNam.setFont(new java.awt.Font("#9Slide03 Source Sans Pro Light", 0, 15)); // NOI18N
        lblNam.setForeground(new java.awt.Color(255, 255, 255));
        lblNam.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNam.setText("Năm sinh");

        lblTen.setFont(new java.awt.Font("#9Slide03 Source Sans Pro Light", 0, 15)); // NOI18N
        lblTen.setForeground(new java.awt.Color(255, 255, 255));
        lblTen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTen.setText("Họ tên");

        lblDienThoai.setFont(new java.awt.Font("#9Slide03 Source Sans Pro Light", 0, 15)); // NOI18N
        lblDienThoai.setForeground(new java.awt.Color(255, 255, 255));
        lblDienThoai.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDienThoai.setText("Số điện thoại");

        lblDienThoai1.setFont(new java.awt.Font("#9Slide03 Source Sans Pro Light", 0, 15)); // NOI18N
        lblDienThoai1.setForeground(new java.awt.Color(255, 255, 255));
        lblDienThoai1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDienThoai1.setText("Địa chỉ");

        txtHoTen.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 14)); // NOI18N
        txtHoTen.setBorder(null);
        txtHoTen.setPreferredSize(new java.awt.Dimension(150, 16));

        txtNamSinh.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 14)); // NOI18N
        txtNamSinh.setBorder(null);
        txtNamSinh.setPreferredSize(new java.awt.Dimension(150, 16));

        txtSoDienThoai.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 14)); // NOI18N
        txtSoDienThoai.setBorder(null);
        txtSoDienThoai.setPreferredSize(new java.awt.Dimension(150, 16));

        lblNgayVL.setFont(new java.awt.Font("#9Slide03 Source Sans Pro Light", 0, 15)); // NOI18N
        lblNgayVL.setForeground(new java.awt.Color(255, 255, 255));
        lblNgayVL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNgayVL.setText("Ngày vào làm");

        lblNgayVaoLam.setBackground(new java.awt.Color(255, 255, 255));
        lblNgayVaoLam.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 14)); // NOI18N
        lblNgayVaoLam.setForeground(new java.awt.Color(255, 255, 255));
        lblNgayVaoLam.setText("12/05/2000");

        txtGioiTinh.setFont(new java.awt.Font("#9Slide03 Source Sans Pro Light", 0, 15)); // NOI18N
        txtGioiTinh.setForeground(new java.awt.Color(255, 255, 255));
        txtGioiTinh.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtGioiTinh.setText("Giới tính");

        radNam.setBackground(new java.awt.Color(53, 55, 70));
        radNam.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 12)); // NOI18N
        radNam.setForeground(new java.awt.Color(255, 255, 255));
        radNam.setText("Nam");
        radNam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N

        radNu.setBackground(new java.awt.Color(53, 55, 70));
        radNu.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 12)); // NOI18N
        radNu.setForeground(new java.awt.Color(255, 255, 255));
        radNu.setText("Nữ");
        radNu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtDiaChi.setColumns(20);
        txtDiaChi.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 14)); // NOI18N
        txtDiaChi.setLineWrap(true);
        txtDiaChi.setRows(5);
        txtDiaChi.setBorder(null);
        jScrollPane1.setViewportView(txtDiaChi);

        lblAddImage.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 14)); // NOI18N
        lblAddImage.setForeground(new java.awt.Color(255, 255, 255));
        lblAddImage.setText("Thêm ảnh mới");
        lblAddImage.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblAddImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddImageMouseClicked(evt);
            }
        });

        lblTen2.setFont(new java.awt.Font("#9Slide03 Source Sans Pro Light", 0, 15)); // NOI18N
        lblTen2.setForeground(new java.awt.Color(255, 255, 255));
        lblTen2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTen2.setText("Ca làm");

        radCa1.setBackground(new java.awt.Color(53, 55, 70));
        radCa1.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 12)); // NOI18N
        radCa1.setForeground(new java.awt.Color(255, 255, 255));
        radCa1.setText("Ca sáng");
        radCa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N

        radCa2.setBackground(new java.awt.Color(53, 55, 70));
        radCa2.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 12)); // NOI18N
        radCa2.setForeground(new java.awt.Color(255, 255, 255));
        radCa2.setText("Ca chiều");
        radCa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N

        radCa3.setBackground(new java.awt.Color(53, 55, 70));
        radCa3.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 12)); // NOI18N
        radCa3.setForeground(new java.awt.Color(255, 255, 255));
        radCa3.setText("Ca tối");
        radCa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N

        lblMaNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien.setFont(new java.awt.Font("#9Slide03 Source Sans Pro SemiB", 0, 20)); // NOI18N
        lblMaNhanVien.setForeground(new java.awt.Color(210, 48, 44));
        lblMaNhanVien.setText("NV001");

        javax.swing.GroupLayout pnlThongTinLayout = new javax.swing.GroupLayout(pnlThongTin);
        pnlThongTin.setLayout(pnlThongTinLayout);
        pnlThongTinLayout.setHorizontalGroup(
            pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinLayout.createSequentialGroup()
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblMa)
                                        .addComponent(txtGioiTinh)
                                        .addComponent(lblNam)
                                        .addComponent(lblTen)
                                        .addComponent(lblDienThoai1)
                                        .addComponent(lblDienThoai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblTen2))
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongTinLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lblNgayVL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))))
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lblAddImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(lblNgayVaoLam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addComponent(radNam, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radNu))
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addComponent(radCa1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radCa2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(radCa3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblMaNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNamSinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlThongTinLayout.setVerticalGroup(
            pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinLayout.createSequentialGroup()
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMa)
                            .addComponent(lblMaNhanVien))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNgayVL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGioiTinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radNu)
                            .addComponent(radNam))
                        .addGap(18, 18, 18)
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDienThoai)))
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addComponent(lblDienThoai1)
                        .addGap(16, 16, 16)
                        .addComponent(lblAddImage))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radCa2)
                        .addComponent(radCa1)
                        .addComponent(radCa3))
                    .addComponent(lblTen2))
                .addGap(88, 88, 88))
        );

        ThemTaiKhoanJPanel.add(pnlThongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, 420));

        rounded1.setBackground(new java.awt.Color(53, 55, 70));
        rounded1.setForeground(new java.awt.Color(37, 213, 54));
        rounded1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblThem.setFont(new java.awt.Font("#9Slide03 Source Sans Pro SemiB", 0, 18)); // NOI18N
        lblThem.setForeground(new java.awt.Color(255, 255, 255));
        lblThem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThem.setText("Thêm");
        lblThem.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThemMouseClicked(evt);
            }
        });
        rounded1.add(lblThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        ThemTaiKhoanJPanel.add(rounded1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, -1, 32));

        pnlQuyen1.setBackground(new java.awt.Color(53, 55, 70));
        pnlQuyen1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tác vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlQuyen1.setForeground(new java.awt.Color(255, 255, 255));

        lblTen1.setFont(new java.awt.Font("#9Slide03 Source Sans Pro Light", 0, 15)); // NOI18N
        lblTen1.setForeground(new java.awt.Color(255, 255, 255));
        lblTen1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTen1.setText("Trạng thái");

        txtLuong.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 14)); // NOI18N
        txtLuong.setBorder(null);
        txtLuong.setPreferredSize(new java.awt.Dimension(150, 16));

        lblLuong.setFont(new java.awt.Font("#9Slide03 Source Sans Pro Light", 0, 15)); // NOI18N
        lblLuong.setForeground(new java.awt.Color(255, 255, 255));
        lblLuong.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLuong.setText("Mức lương");

        radConLam.setBackground(new java.awt.Color(53, 55, 70));
        radConLam.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 12)); // NOI18N
        radConLam.setForeground(new java.awt.Color(255, 255, 255));
        radConLam.setText("Còn làm");
        radConLam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N

        radNghiLam.setBackground(new java.awt.Color(53, 55, 70));
        radNghiLam.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 12)); // NOI18N
        radNghiLam.setForeground(new java.awt.Color(255, 255, 255));
        radNghiLam.setText("Nghỉ làm");
        radNghiLam.setEnabled(false);
        radNghiLam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N

        javax.swing.GroupLayout pnlQuyen1Layout = new javax.swing.GroupLayout(pnlQuyen1);
        pnlQuyen1.setLayout(pnlQuyen1Layout);
        pnlQuyen1Layout.setHorizontalGroup(
            pnlQuyen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuyen1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlQuyen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTen1)
                    .addComponent(lblLuong))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlQuyen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlQuyen1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(radConLam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radNghiLam))
                    .addGroup(pnlQuyen1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(txtLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        pnlQuyen1Layout.setVerticalGroup(
            pnlQuyen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuyen1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlQuyen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlQuyen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radNghiLam)
                        .addComponent(radConLam))
                    .addComponent(lblTen1))
                .addGap(18, 18, 18)
                .addGroup(pnlQuyen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLuong))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        ThemTaiKhoanJPanel.add(pnlQuyen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 290, -1));

        pnlQuyen.setBackground(new java.awt.Color(53, 55, 70));
        pnlQuyen.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tác vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlQuyen.setForeground(new java.awt.Color(255, 255, 255));

        cbxTongQuan.setBackground(new java.awt.Color(53, 55, 70));
        cbxTongQuan.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 12)); // NOI18N
        cbxTongQuan.setForeground(new java.awt.Color(255, 255, 255));
        cbxTongQuan.setText("Tổng quan");
        cbxTongQuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N

        cbxSanPham.setBackground(new java.awt.Color(53, 55, 70));
        cbxSanPham.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 12)); // NOI18N
        cbxSanPham.setForeground(new java.awt.Color(255, 255, 255));
        cbxSanPham.setText("Sản phẩm");
        cbxSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N

        cbxKhuyenMai.setBackground(new java.awt.Color(53, 55, 70));
        cbxKhuyenMai.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 12)); // NOI18N
        cbxKhuyenMai.setForeground(new java.awt.Color(255, 255, 255));
        cbxKhuyenMai.setText("Khuyến mãi");
        cbxKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N

        cbxDoanhThu.setBackground(new java.awt.Color(53, 55, 70));
        cbxDoanhThu.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 12)); // NOI18N
        cbxDoanhThu.setForeground(new java.awt.Color(255, 255, 255));
        cbxDoanhThu.setText("Doanh thu");
        cbxDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N

        cbxNhapHang.setBackground(new java.awt.Color(53, 55, 70));
        cbxNhapHang.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 12)); // NOI18N
        cbxNhapHang.setForeground(new java.awt.Color(255, 255, 255));
        cbxNhapHang.setText("Nhập hàng");
        cbxNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N

        cbxDonHang.setBackground(new java.awt.Color(53, 55, 70));
        cbxDonHang.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 12)); // NOI18N
        cbxDonHang.setForeground(new java.awt.Color(255, 255, 255));
        cbxDonHang.setText("Đơn hàng");
        cbxDonHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N

        cbxThongKe.setBackground(new java.awt.Color(53, 55, 70));
        cbxThongKe.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 12)); // NOI18N
        cbxThongKe.setForeground(new java.awt.Color(255, 255, 255));
        cbxThongKe.setText("Thống kê");
        cbxThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N

        cbxQuanLyNhanVien.setBackground(new java.awt.Color(53, 55, 70));
        cbxQuanLyNhanVien.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 12)); // NOI18N
        cbxQuanLyNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        cbxQuanLyNhanVien.setText("Quản lí nhân viên");
        cbxQuanLyNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N

        cbxQuanLyDanhMuc.setBackground(new java.awt.Color(53, 55, 70));
        cbxQuanLyDanhMuc.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 12)); // NOI18N
        cbxQuanLyDanhMuc.setForeground(new java.awt.Color(255, 255, 255));
        cbxQuanLyDanhMuc.setText("Quản lí danh mục");
        cbxQuanLyDanhMuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N

        cbxKhachHang.setBackground(new java.awt.Color(53, 55, 70));
        cbxKhachHang.setFont(new java.awt.Font("#9Slide03 Source Sans Pro", 0, 12)); // NOI18N
        cbxKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        cbxKhachHang.setText("Khách hàng");
        cbxKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unchecked.png"))); // NOI18N

        javax.swing.GroupLayout pnlQuyenLayout = new javax.swing.GroupLayout(pnlQuyen);
        pnlQuyen.setLayout(pnlQuyenLayout);
        pnlQuyenLayout.setHorizontalGroup(
            pnlQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuyenLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxTongQuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxDonHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxQuanLyDanhMuc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(pnlQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxQuanLyNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlQuyenLayout.createSequentialGroup()
                        .addGroup(pnlQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbxNhapHang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                .addComponent(cbxSanPham, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cbxKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
        );
        pnlQuyenLayout.setVerticalGroup(
            pnlQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuyenLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxSanPham)
                    .addComponent(cbxTongQuan))
                .addGap(15, 15, 15)
                .addGroup(pnlQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxNhapHang)
                    .addComponent(cbxDonHang))
                .addGap(15, 15, 15)
                .addGroup(pnlQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxThongKe)
                    .addComponent(cbxQuanLyNhanVien))
                .addGap(15, 15, 15)
                .addGroup(pnlQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxDoanhThu)
                    .addComponent(cbxKhuyenMai))
                .addGap(15, 15, 15)
                .addGroup(pnlQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxQuanLyDanhMuc)
                    .addComponent(cbxKhachHang))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        ThemTaiKhoanJPanel.add(pnlQuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 290, 283));

        rounded2.setBackground(new java.awt.Color(53, 55, 70));
        rounded2.setForeground(new java.awt.Color(210, 57, 44));
        rounded2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNhapLai.setFont(new java.awt.Font("#9Slide03 Source Sans Pro SemiB", 0, 18)); // NOI18N
        lblNhapLai.setForeground(new java.awt.Color(255, 255, 255));
        lblNhapLai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNhapLai.setText("Nhập lại");
        lblNhapLai.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblNhapLai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNhapLaiMouseClicked(evt);
            }
        });
        rounded2.add(lblNhapLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        ThemTaiKhoanJPanel.add(rounded2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, -1, 32));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ThemTaiKhoanJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ThemTaiKhoanJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void lblAddImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddImageMouseClicked
        if (SwingUtilities.isLeftMouseButton(evt)) {
            try {
               File file =  GUI.Sweet.SweetFileChooser.ImageFileChooser();
                if(file!=null)
                lblAnh.setIcon(resizeImage(ImageIO.read(file), 180, 240));} catch (IOException ex) {
                Logger.getLogger(ThemTaiKhoanJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_lblAddImageMouseClicked

    private void lblThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemMouseClicked
       if (SwingUtilities.isLeftMouseButton(evt))
        if (GUI.Sweet.SweetAlert.showSweetOption(new javax.swing.JFrame(), "Thêm mới tài khoản", "Xác nhận thêm?", 0) == 1) {
            if (isNotFill()) {
                GUI.Sweet.SweetAlert.showSweetAlert(new javax.swing.JFrame(), "Lỗi", "Không được bỏ trống", 0);
            } else {
                NhanVien = new NhanVienDTO(lblMaNhanVien.getText(), txtHoTen.getText(), groupGioiTinh.getSelection().getActionCommand(), txtNamSinh.getText(), txtSoDienThoai.getText(), txtDiaChi.getText(), groupTrangThai.getSelection().getActionCommand(), txtLuong.getText(), DateTime.getCurrentTimestamp(), groupCaLam.getSelection().getActionCommand(),saveImage(lblMaNhanVien.getText()));
                Account = new AccountDTO(lblMaNhanVien.getText(), "123456", getRole(), "Nhân viên");
                
                if (quanlycuahanggiay.quanlycuahanggiay.NhanVienBUS.add(NhanVien)) {
                    quanlycuahanggiay.quanlycuahanggiay.AccountBUS.add(Account);
                    
                    GUI.Sweet.SweetAlert.showSweetAlert(new javax.swing.JFrame(), "Thành công", "Lưu thành công", 0);
                    fillBlank();
                    lblMaNhanVien.setText(quanlycuahanggiay.quanlycuahanggiay.NhanVienBUS.getLatest());
                    quanlycuahanggiay.quanlycuahanggiay.AccountBUS.fetchAll();
                }

            }
        }
    }//GEN-LAST:event_lblThemMouseClicked

    private boolean isNotFill() {
        if (txtHoTen.getText().equals("") || txtNamSinh.getText().equals("") || txtSoDienThoai.getText().equals("") || txtDiaChi.getText().equals("") || txtLuong.getText().equals("")) {
            return true;
        }
        return false;
    }
    
    private void fillBlank(){
       txtHoTen.setText("");
       txtNamSinh.setText("");
       txtSoDienThoai.setText("");
       txtDiaChi.setText("");
       txtLuong.setText("");
       arrButton.forEach(item -> item.setSelected(false));
       lblAnh.setIcon(null);
    }
    private void lblNhapLaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhapLaiMouseClicked
        if(GUI.Sweet.SweetAlert.showSweetOption(new javax.swing.JFrame(), "Nhập lại", "Bạn có muốn nhập lại?", 3)==1)
        fillBlank();
    }//GEN-LAST:event_lblNhapLaiMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.Rounded ThemTaiKhoanJPanel;
    private javax.swing.JCheckBox cbxDoanhThu;
    private javax.swing.JCheckBox cbxDonHang;
    private javax.swing.JCheckBox cbxKhachHang;
    private javax.swing.JCheckBox cbxKhuyenMai;
    private javax.swing.JCheckBox cbxNhapHang;
    private javax.swing.JCheckBox cbxQuanLyDanhMuc;
    private javax.swing.JCheckBox cbxQuanLyNhanVien;
    private javax.swing.JCheckBox cbxSanPham;
    private javax.swing.JCheckBox cbxThongKe;
    private javax.swing.JCheckBox cbxTongQuan;
    private javax.swing.ButtonGroup groupCaLam;
    private javax.swing.ButtonGroup groupGioiTinh;
    private javax.swing.ButtonGroup groupTrangThai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddImage;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JLabel lblDienThoai;
    private javax.swing.JLabel lblDienThoai1;
    private javax.swing.JLabel lblLuong;
    private javax.swing.JLabel lblMa;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblNam;
    private javax.swing.JLabel lblNgayVL;
    private javax.swing.JLabel lblNgayVaoLam;
    private javax.swing.JLabel lblNhapLai;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblTen1;
    private javax.swing.JLabel lblTen2;
    private javax.swing.JLabel lblThem;
    private javax.swing.JPanel pnlQuyen;
    private javax.swing.JPanel pnlQuyen1;
    private javax.swing.JPanel pnlThongTin;
    private javax.swing.JRadioButton radCa1;
    private javax.swing.JRadioButton radCa2;
    private javax.swing.JRadioButton radCa3;
    private javax.swing.JRadioButton radConLam;
    private javax.swing.JRadioButton radNam;
    private javax.swing.JRadioButton radNghiLam;
    private javax.swing.JRadioButton radNu;
    private GUI.Rounded rounded1;
    private GUI.Rounded rounded2;
    private javax.swing.JTextArea txtDiaChi;
    private javax.swing.JLabel txtGioiTinh;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtNamSinh;
    private javax.swing.JTextField txtSoDienThoai;
    // End of variables declaration//GEN-END:variables
}
